#!/usr/bin/env python3
import itertools
import os
import sys

from os.path import dirname, join, abspath
sys.path.insert(0, abspath(join(dirname(__file__), '..')))

from gen_convert_common import (
  types, int_types, signed_types, unsigned_types, float_types, int64_types, float64_types,
  vector_sizes, half_sizes, saturation, rounding_modes, float_prefix, float_suffix, bool_type,
  unsigned_type, sizeof_type, limit_max, limit_min, conditional_guard, spirv_fn_name
)

# OpenCL built-in library: type conversion functions
#
# Copyright (c) 2013 Victor Oliveira <victormatheus@gmail.com>
# Copyright (c) 2013 Jesse Towner <jessetowner@lavabit.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# This script generates the file convert-spirv.cl, which contains all of the
# SPIR-V conversion functions.


print("""/* !!!! AUTOGENERATED FILE generated by convert_type.py !!!!!

   DON'T CHANGE THIS FILE. MAKE YOUR CHANGES TO convert_type.py AND RUN:
   $ ./generate-conversion-type-cl.sh

   OpenCL type conversion functions

   Copyright (c) 2013 Victor Oliveira <victormatheus@gmail.com>
   Copyright (c) 2013 Jesse Towner <jessetowner@lavabit.com>

   Permission is hereby granted, free of charge, to any person obtaining a copy
   of this software and associated documentation files (the "Software"), to deal
   in the Software without restriction, including without limitation the rights
   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
   copies of the Software, and to permit persons to whom the Software is
   furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in
   all copies or substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
   THE SOFTWARE.
*/

#include <spirv/spirv.h>

#ifdef cl_khr_fp64
#pragma OPENCL EXTENSION cl_khr_fp64 : enable

#if defined(__EMBEDDED_PROFILE__) && !defined(cles_khr_int64)
#error Embedded profile that supports cl_khr_fp64 also has to support cles_khr_int64
#endif

#endif

#ifdef cles_khr_int64
#pragma OPENCL EXTENSION cles_khr_int64 : enable
#endif

""")


# Return spirv_fn_name result or internal implementation detail function name.
def spirv_fn_name_with_impl(src, dst, size='', mode='', sat=''):
  name = spirv_fn_name(src, dst, size, mode, sat)
  if name is None:
    if src in signed_types and dst in unsigned_types and sat == '':
      name = "__spirv_clc_SToUConvert_R{DST}{N}{MODE}".format(DST=dst, N=size, MODE=mode)
    elif src in unsigned_types and dst in signed_types and sat == '':
      name = "__spirv_clc_UToSConvert_R{DST}{N}{MODE}".format(DST=dst, N=size, MODE=mode)

  return name


def implicitly_declare_impl_fn(src, dst, size, mode):
  print("""_CLC_DECL _CLC_OVERLOAD
{DST}{N} {FN}({SRC}{N} x);
  """.format(DST=dst, SRC=src, N=size, FN=spirv_fn_name_with_impl(src, dst, size, mode)))

# Implicitly declare implementation detail functions.
for src in unsigned_types:
  for dst in signed_types:
    for size in vector_sizes:
      implicitly_declare_impl_fn(src, dst, size, '')
      for mode in rounding_modes:
        implicitly_declare_impl_fn(src, dst, size, mode)

for src in signed_types:
  for dst in unsigned_types:
    for size in vector_sizes:
      implicitly_declare_impl_fn(src, dst, size, '')
      for mode in rounding_modes:
        implicitly_declare_impl_fn(src, dst, size, mode)

# Default Conversions
#
# All conversions are in accordance with the OpenCL specification,
# which cites the C99 conversion rules.
#
# Casting from floating point to integer results in conversions
# with truncation, so it should be suitable for the default convert
# functions.
#
# Conversions from integer to floating-point, and floating-point to
# floating-point through casting is done with the default rounding
# mode. While C99 allows dynamically changing the rounding mode
# during runtime, it is not a supported feature in OpenCL according
# to Section 7.1 - Rounding Modes in the OpenCL 1.2 specification.
#
# Therefore, we can assume for optimization purposes that the
# rounding mode is fixed to round-to-nearest-even. Platform target
# authors should ensure that the rounding-control registers remain
# in this state, and that this invariant holds.
#
# Also note, even though the OpenCL specification isn't entirely
# clear on this matter, we implement all rounding mode combinations
# even for integer-to-integer conversions. When such a conversion
# is used, the rounding mode is ignored.
def generate_default_conversion(src, dst, mode):
  close_conditional = conditional_guard(src, dst)

  # scalar conversions
  print("""_CLC_DEF _CLC_OVERLOAD
{DST} {FN}({SRC} x)
{{
  return ({DST})x;
}}
""".format(SRC=src, DST=dst, FN=spirv_fn_name_with_impl(src, dst, mode=mode)))

  # vector conversions, done through decomposition to components
  for size, half_size in half_sizes.items():
    print("""_CLC_DEF _CLC_OVERLOAD
{DST}{N} {FN}({SRC}{N} x)
{{
  return ({DST}{N})({FN_H}(x.lo), {FN_H}(x.hi));
}}
""".format(SRC=src, DST=dst, N=size,
           FN=spirv_fn_name_with_impl(src, dst, size=size, mode=mode),
           FN_H=spirv_fn_name_with_impl(src, dst, size=half_size, mode=mode)))

  # 3-component vector conversions
  print("""_CLC_DEF _CLC_OVERLOAD
{DST}3 {FN_3}({SRC}3 x)
{{
  return ({DST}3)({FN_2}(x.s01), {FN_1}(x.s2));
}}""".format(SRC=src, DST=dst, M=mode,
             FN_3=spirv_fn_name_with_impl(src, dst, size='3', mode=mode),
             FN_2=spirv_fn_name_with_impl(src, dst, size='2', mode=mode),
             FN_1=spirv_fn_name_with_impl(src, dst, mode=mode)))

  if close_conditional:
    print("#endif")


# `__spirv_SConvert`, `__spirv_UConvert`, and `__spirv_clc_SToUConvert`, `__spirv_clc_UToSConvert`
# (not in header, only for implementation use)
for src, dst in itertools.combinations(int_types, 2):
  generate_default_conversion(src, dst, '')
  for mode in rounding_modes:
    generate_default_conversion(src, dst, mode)

# `__spirv_FConvert`
for src, dst in itertools.combinations(float_types, 2):
  generate_default_conversion(src, dst, '')


# Saturated Conversions To Integers
#
# These functions are dependent on the unsaturated conversion functions
# generated above, and use clamp, max, min, and select to eliminate
# branching and vectorize the conversions.
#
# Again, as above, we allow all rounding modes for integer-to-integer
# conversions with saturation.
def generate_saturated_conversion(src, dst, size):
  # Header
  close_conditional = conditional_guard(src, dst)
  print("""_CLC_DEF _CLC_OVERLOAD
{DST}{N} {FN}({SRC}{N} x)
{{""".format(DST=dst, SRC=src, N=size, FN=spirv_fn_name_with_impl(src, dst, size=size, sat='_sat')))

  # FIXME: This is a work around for lack of select function with
  # signed third argument when the first two arguments are unsigned types.
  # We cast to the signed type for sign-extension, then do a bitcast to
  # the unsigned type.
  bool_prefix = spirv_fn_name_with_impl('int', bool_type[dst], size=size)
  bool_suffix = ""
  if dst in unsigned_types:
    bool_prefix = "as_{DST}{N}({BOOL}".format(DST=dst, BOOL=bool_prefix, N=size);
    bool_suffix = ")"

  # Body
  if src == dst:

    # Conversion between same types
    print("  return x;")

  elif src in float_types:

    # Conversion from float to int
    print("""  {DST}{N} y = {FN}(x);
  y = __spirv_ocl_select(y, ({DST}{N}){DST_MIN}, {BP}(x < ({SRC}{N}){DST_MIN}){BS});
  y = __spirv_ocl_select(y, ({DST}{N}){DST_MAX}, {BP}(x > ({SRC}{N}){DST_MAX}){BS});
  return y;""".format(SRC=src, DST=dst, N=size,
      DST_MIN=limit_min[dst], DST_MAX=limit_max[dst],
      BP=bool_prefix, BS=bool_suffix,
      FN=spirv_fn_name_with_impl(dst, dst, size=size)))

  else:

    # Integer to integer convesion with sizeof(src) == sizeof(dst)
    if sizeof_type[src] == sizeof_type[dst]:
      if src in unsigned_types:
        print("  x = __spirv_ocl_u_min(x, ({SRC}){DST_MAX});"
          .format(SRC=src, DST_MAX=limit_max[dst]))
      else:
        print("  x = __spirv_ocl_u_max(x, ({SRC})0);".format(SRC=src))

    # Integer to integer conversion where sizeof(src) > sizeof(dst)
    elif sizeof_type[src] > sizeof_type[dst]:
      if src in unsigned_types:
        print("  x = __spirv_ocl_u_min(x, ({SRC}){DST_MAX});"
          .format(SRC=src, DST_MAX=limit_max[dst]))
      else:
        print("  x = __spirv_ocl_u_clamp(x, ({SRC}){DST_MIN}, ({SRC}){DST_MAX});"
          .format(SRC=src, DST_MIN=limit_min[dst], DST_MAX=limit_max[dst]))

    # Integer to integer conversion where sizeof(src) < sizeof(dst)
    elif src not in unsigned_types and dst in unsigned_types:
        print("  x = __spirv_ocl_u_max(x, ({SRC})0);".format(SRC=src))

    print("  return {FN}(x);".format(FN=spirv_fn_name_with_impl(src, dst, size=size)))

  # Footer
  print("}")
  if close_conditional:
    print("#endif")


# `__spirv_SatConvertUToS`
for src in unsigned_types:
  for dst in signed_types:
    for size in vector_sizes:
      generate_saturated_conversion(src, dst, size)

# `__spirv_SatConvertSToU`
for src in signed_types:
  for dst in unsigned_types:
    for size in vector_sizes:
      generate_saturated_conversion(src, dst, size)


def generate_saturated_conversion_with_rounding(src, dst, size, mode):
  # header
  close_conditional = conditional_guard(src, dst)

  # body
  print("""_CLC_DEF _CLC_OVERLOAD
{DST}{N} {FN_WITH_MODE}({SRC}{N} x)
{{
  return {FN_WOUT_MODE}(x);
}}
""".format(DST=dst, SRC=src, N=size,
           FN_WITH_MODE=spirv_fn_name_with_impl(src, dst, size=size, mode=mode, sat='_sat'),
           FN_WOUT_MODE=spirv_fn_name_with_impl(src, dst, size=size, sat='_sat')))

  # Footer
  if close_conditional:
    print("#endif")


# `__spirv_SatConvertUToS` w/ rounding
for src in unsigned_types:
  for dst in signed_types:
    for size in vector_sizes:
      for mode in rounding_modes:
        generate_saturated_conversion_with_rounding(src, dst, size, mode)

# `__spirv_SatConvertSToU` w/ rounding
for src in signed_types:
  for dst in unsigned_types:
    for size in vector_sizes:
      for mode in rounding_modes:
        generate_saturated_conversion_with_rounding(src, dst, size, mode)

# Conversions To/From Floating-Point With Rounding
#
# Note that we assume as above that casts from floating-point to
# integer are done with truncation, and that the default rounding
# mode is fixed to round-to-nearest-even, as per C99 and OpenCL
# rounding rules.
#
# These functions rely on the use of abs, ceil, fabs, floor,
# nextafter, sign, rint and the above generated conversion functions.
#
# Only conversions to integers can have saturation.
def generate_float_conversion(src, dst, size, mode, sat):
  # Header
  close_conditional = conditional_guard(src, dst)
  print("""_CLC_DEF _CLC_OVERLOAD
{DST}{N} {NAME}({SRC}{N} x)
{{""".format(SRC=src, DST=dst, N=size,
             NAME=spirv_fn_name_with_impl(src, dst, size=size, mode=mode, sat=sat)))

  # Perform conversion
  if mode == '':
    fallback_fn_name = spirv_fn_name_with_impl(src, dst, size=size, mode='_rte', sat=sat)
    print("  return {FN}(x);".format(FN=fallback_fn_name))
  elif dst in int_types:
    if mode == '_rte':
      print("  x = __spirv_ocl_rint(x);");
    elif mode == '_rtp':
      print("  x = __spirv_ocl_ceil(x);");
    elif mode == '_rtn':
      print("  x = __spirv_ocl_floor(x);");
    print("  return {FN}(x);".format(FN=spirv_fn_name_with_impl(src, dst, size=size, sat=sat)))
  elif mode == '_rte':
    print("  return {FN}(x);".format(FN=spirv_fn_name_with_impl(src, dst, size=size)))
  else:
    print("  {DST}{N} r = {FN}(x);".format(DST=dst, N=size,
                                           FN=spirv_fn_name_with_impl(src, dst, size=size)))
    print("  {SRC}{N} y = {FN}(y);".format(SRC=src, N=size,
                                           FN=spirv_fn_name_with_impl(src, src, size=size)))
    if mode == '_rtz':
      if src in int_types:
        print("  {USRC}{N} abs_x = __spirv_ocl_u_abs(x);".format(USRC=unsigned_type[src], N=size))
        print("  {USRC}{N} abs_y = __spirv_ocl_u_abs(y);".format(USRC=unsigned_type[src], N=size))
      else:
        print("  {SRC}{N} abs_x = __spirv_ocl_fabs(x);".format(SRC=src, N=size))
        print("  {SRC}{N} abs_y = __spirv_ocl_fabs(y);".format(SRC=src, N=size))
      print("  return __spirv_ocl_select(r, __spirv_ocl_nextafter(r, __spirv_ocl_sign(r) * "
            "({DST}{N})-INFINITY), {FN}(abs_y > abs_x));"
        .format(DST=dst, N=size, FN=spirv_fn_name_with_impl('int', bool_type[dst], size=size)))
    if mode == '_rtp':
      print("  return __spirv_ocl_select(r, __spirv_ocl_nextafter(r, ({DST}{N})INFINITY), "
            "{FN}(y < x));"
        .format(DST=dst, N=size, FN=spirv_fn_name_with_impl('int', bool_type[dst], size=size)))
    if mode == '_rtn':
      print("  return __spirv_ocl_select(r, __spirv_ocl_nextafter(r, ({DST}{N})-INFINITY), "
            "{FN}(y > x));"
        .format(DST=dst, N=size, FN=spirv_fn_name_with_impl('int', bool_type[dst], size=size)))

  # Footer
  print("}")
  if close_conditional:
    print("#endif")


# `__spirv_ConvertFToU` and `__spirv_ConvertFToS`
for src in float_types:
  for dst in int_types:
    for size in vector_sizes:
      generate_float_conversion(src, dst, size, '', '')
      for mode in rounding_modes:
        generate_float_conversion(src, dst, size, mode, '')

# `__spirv_ConvertUToF` and `__spirv_ConvertSToF`
for src in int_types:
  for dst in float_types:
    for size in vector_sizes:
      generate_float_conversion(src, dst, size, '', '')
      for mode in rounding_modes:
        generate_float_conversion(src, dst, size, mode, '')
