= SYCL(TM) Proposals: Platform Default Contexts
James Brodman <james.brodman@intel.com>
v0.1
:source-highlighter: pygments
:icons: font
:y: icon:check[role="green"]
:n: icon:times[role="red"]

== Platform Default Contexts

This extension adds the notion of a default SYCL context per SYCL platform. The default context for each platform contains all devices in the platform.

The platform class gains three new methods:

[cols="^60a,40"]
|===
| Member Function | Description

|
[source,c++]
----
context get_default_context()
----

| Returns the current default context for this `platform`

|
[source,c++]
----
void push_default_context(const context &NewContext)
----

| Sets the current default context to `NewContext`. The previous default context is saved.

|
[source,c++]
----
void pop_default_context()
----

| Removes the current default context and restores the previous default context if applicable or throws a `runtime_error` if there is no valid context to restore.
|===

This extension also modifies the behavior of `queue` constructors. Queues will no longer create a new `context` upon consruction. Instead, they will use the default context from the device's platform.
