# Async Group Copy Extension for DPC++: SYCL_EXT_ONEAPI_ASYNC_GROUP_COPY
:source-highlighter: coderay
:coderay-linenums-mode: table
:dpcpp: pass:[DPC++]

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en

:blank: pass:[ +]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}


== Notice

Copyright (c) 2021-2021 Intel Corporation.  All rights reserved.

IMPORTANT: This specification is a draft.

NOTE: Khronos(R) is a registered trademark and SYCL(TM) and SPIR(TM) are
trademarks of The Khronos Group Inc.  OpenCL(TM) is a trademark of Apple Inc.
used by permission by Khronos.

This extension is written against the SYCL 2020 revision 4 specification.  All
references below to the "core SYCL specification" or to section numbers in the
SYCL specification refer to that revision.

## Contributors

* Gordon Brown
* Tadej Ciglaric
* Jack Kirk
* Finlay Marno

## Introduction

This document proposes `async_group_copy`, which will generalize
`async_work_group_copy` to work with sub-groups as well as work-groups.
A `wait_for` function will also be also be added to block until the memory
copy is complete and to ensure memory consistency for the group, this will use
the same groups as `async_group_copy`.

## Feature test macro

This extension provides a feature-test macro as described in the core SYCL
specification section 6.3.3 "Feature test macros". Therefore, an implementation
supporting this extension must predefine the macro
SYCL_EXT_ONEAPI_ASYNC_GROUP_COPY to one of the values defined in the table
below. Applications can test for the existence of this macro to determine if the
implementation supports this feature, or applications can test the macro’s value
to determine which of the extension’s APIs the implementation supports.

[%header,cols="1,5"]
|===
|Value |Description
|1     |Initial extension implementation.
|===


## New `async_group_copy` function.
`async_group_copy` will work very similarly to `async_work_group_copy`, but
with the ability to utilize individual sub-groups. The group will be provided
as a template parameter, in the same fashion as `group_barrier`.
`async_group_copy` is intended as a potential optimization, and may add more
overhead than a simple synchronous implementation in some cases.

`async_group_copy` will asynchronously copy a given number of values of type
`dataT` from global memory to local memory or from local memory to global
memory. If an asynchorous copy is not supported then `async_group_copy` will
fall back on a synchronous copy. `async_group_copy` is a free function with the
following properties:

* The work-items will not necessarily be synchronized, so must have a
  consistent view of the memory before the invocation.
* The order of operations is not specified.
* All work-items of the group are required to call the function with the same
  arguments, otherwise the behaviour is undefined.
* All work-items of the group are required to call the function in convergent
  control flow, otherwise the behaviour is undefined.
* The type of `dataT` should be a scalar or vector type.
* The data written by `async_group_copy` should not be read until `wait_for`
  has been called on the returned `device_event`.

The structs `dest_stride` and `src_stride` have been introduced to reduce errors
when specifying the stride.

Note that the destination and source arguments have been swapped to be more in
line with other SYCL copy functions.

```c++
namespace sycl::ext::oneapi {

struct dest_stride {
       std::size_t value;
};

struct src_stride {
       std::size_t value;
};

template <typename Group, typename dataT>
device_event async_group_copy(Group group, sycl::decorated_local_ptr<dataT> src, sycl::decorated_global_ptr<dataT> dest, size_t count);

template <typename Group, typename dataT>
device_event async_group_copy(Group group, sycl::decorated_global_ptr<dataT> src, sycl::decorated_local_ptr<dataT> dest, size_t count);

template <typename Group, typename dataT>
device_event async_group_copy(Group group, sycl::decorated_local_ptr<dataT> src, sycl::decorated_global_ptr<dataT> dest, size_t count, dest_stride destStride);

template <typename Group, typename dataT>
device_event async_group_copy(Group group, sycl::decorated_global_ptr<dataT> src, sycl::decorated_local_ptr<dataT> dest, size_t count, src_stride srcStride);
} // namespace sycl::ext::oneapi
```

## New `wait_for` function
`wait_for` will work very similarly to `nd_item::wait_for` or `group::wait_for`,
but with the ability to utilize individual sub-groups. The group will be provided
as a template parameter, in the same fashion as `group_barrier`.

`wait_for` will block until all the asychronous copies represented by the
`device_event` arguments are complete. Data written to a location by `async_group_copy`
should not be read until `wait_for` has been called with the returned
`device_event`. `wait_for` will also act as a group barrier to ensure memory
consistency between the work-items of the group.

`wait_for` is a free function with the following properties:

* The group should be the same as the group used in all invocations of
  `async_group_copy` that returned the `device_event` arguments or the behaviour is undefined.
* All work-items of the group are required to call the function in convergent
  control flow, otherwise the behaviour is undefined.


NOTE: For NVIDIA architectures of sm_80 or higher, the group will be blocked until all
outstanding async_group_copy requests are completed.

```c++
namespace sycl::ext::oneapi {
    template <typename Group, typename eventTN>
    void wait_for(Group group, eventTN... Events) noexcept;
}  // namespace sycl
```

## Revision History

[frame="none",options="header"]
|======================
|Rev |Date       |Author        |Changes
|1   |2021-11-08 |Finlay Marno  |Initial working draft.
|======================
