; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --include-generated-funcs --version 5
; RUN: opt -bugpoint-enable-legacy-pm -globaloffset %s -S -o - | FileCheck %s

; Make sure that the cloned function (main_func_with_offset) gets its own dbg
; node, DBG5 vs DBG10 in the check below.

target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

define void @main_func(ptr %this, ptr %group) !dbg !5 {
entry:
  call void @call_func_1()
  ret void
}

define void @call_func_1() {
entry:
  %0 = call ptr @llvm.nvvm.implicit.offset()
  ret void
}

; Function Attrs: nounwind speculatable memory(none)
declare ptr @llvm.nvvm.implicit.offset() #0

attributes #0 = { nounwind speculatable memory(none) }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 0.0.0", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "ParFor_WG_local_dilatation.cpp", directory: "llvm/tickets/DISubprogram/temps")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 1, !"sycl-device", i32 1}
!5 = distinct !DISubprogram(name: "operator()", linkageName: "main_func", scope: !7, file: !6, line: 26, type: !8, scopeLine: 26, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, declaration: !9, retainedNodes: !2)
!6 = !DIFile(filename: "../mrm-219/ParFor_WG_local_dilatation.cpp", directory: "llvm/tickets/DISubprogram/temps")
!7 = distinct !DICompositeType(tag: DW_TAG_class_type, file: !6, line: 26, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2)
!8 = distinct !DISubroutineType(types: !2)
!9 = !DISubprogram(name: "operator()", scope: !7, file: !6, line: 26, type: !8, scopeLine: 26, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit)
!10 = !DILocalVariable(name: "Func", arg: 2, scope: !11, file: !12, line: 180, type: !20)
!11 = distinct !DISubprogram(name: "parallel_for_work_item<(lambda at ../mrm-219/ParFor_WG_local_dilatation.cpp:28:19)>", linkageName: "call_func_1", scope: !13, file: !12, line: 180, type: !16, scopeLine: 180, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: !0, templateParams: !2, declaration: !17, retainedNodes: !2)
!12 = !DIFile(filename: "build/bin/../include/sycl/group.hpp", directory: "llvm")
!13 = distinct !DICompositeType(tag: DW_TAG_class_type, name: "group<2>", scope: !14, file: !12, line: 103, size: 512, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2, templateParams: !2, identifier: "_ZTSN4sycl3_V15groupILi2EEE")
!14 = !DINamespace(name: "_V1", scope: !15, exportSymbols: true)
!15 = !DINamespace(name: "sycl", scope: null)
!16 = distinct !DISubroutineType(types: !2)
!17 = !DISubprogram(name: "parallel_for_work_item<(lambda at ../mrm-219/ParFor_WG_local_dilatation.cpp:28:19)>", linkageName: "call_func_1", scope: !13, file: !12, line: 180, type: !16, scopeLine: 180, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit, templateParams: !18)
!18 = !{!19}
!19 = !DITemplateTypeParameter(name: "WorkItemFunctionT", type: !20)
!20 = distinct !DICompositeType(tag: DW_TAG_class_type, scope: !5, file: !6, line: 28, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: !2)
!21 = !DILocation(line: 180, column: 49, scope: !11)
; CHECK-LABEL: define void @main_func(
; CHECK-SAME: ptr [[THIS:%.*]], ptr [[GROUP:%.*]]) !dbg [[DBG5:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @call_func_1()
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @main_func_with_offset(
; CHECK-SAME: ptr [[TMP0:%.*]], ptr [[TMP1:%.*]], ptr [[TMP2:%.*]]) !dbg [[DBG10:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @call_func_1_with_offset(ptr [[TMP2]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @call_func_1() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define void @call_func_1_with_offset(
; CHECK-SAME: ptr [[TMP0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: [[META1:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, enums: [[META2:![0-9]+]], retainedTypes: [[META2]], globals: [[META2]], imports: [[META2]], splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "ParFor_WG_local_dilatation.cpp", directory: {{.*}})
; CHECK: [[META2]] = !{}
; CHECK: [[META3:![0-9]+]] = !{i32 2, !"Debug Info Version", i32 3}
; CHECK: [[META4:![0-9]+]] = !{i32 1, !"sycl-device", i32 1}
; CHECK: [[DBG5]] = distinct !DISubprogram(name: "operator()", linkageName: "main_func", scope: [[META7:![0-9]+]], file: [[META6:![0-9]+]], line: 26, type: [[META8:![0-9]+]], scopeLine: 26, flags: DIFlagPrototyped, spFlags: DISPFlagLocalToUnit | DISPFlagDefinition, unit: [[META0]], declaration: [[META9:![0-9]+]], retainedNodes: [[META2]])
; CHECK: [[META6]] = !DIFile(filename: "../mrm-219/ParFor_WG_local_dilatation.cpp", directory: {{.*}})
; CHECK: [[META7]] = distinct !DICompositeType(tag: DW_TAG_class_type, file: [[META6]], line: 26, size: 8, flags: DIFlagTypePassByValue | DIFlagNonTrivial, elements: [[META2]])
; CHECK: [[META8]] = distinct !DISubroutineType(types: [[META2]])
; CHECK: [[META9]] = !DISubprogram(name: "operator()", scope: [[META7]], file: [[META6]], line: 26, type: [[META8]], scopeLine: 26, flags: DIFlagPublic | DIFlagPrototyped, spFlags: DISPFlagLocalToUnit)
; CHECK: [[DBG10]] = distinct !DISubprogram(name: "operator()_with_offset", linkageName: "main_func_with_offset", scope: [[META6]], file: [[META6]], type: [[META8]], flags: DIFlagArtificial, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]])
;.
