; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -bugpoint-enable-legacy-pm -localaccessortosharedmemory %s -S -o - | FileCheck %s

target datalayout = "e-i64:64-i128:128-v16:16-v32:32-n16:32:64"
target triple = "nvptx64-nvidia-cuda"

; This test checks that no transformation is applied when there are no entry points.

define void @_ZTS14example_kernel(ptr addrspace(3) %a, ptr addrspace(1) %b, i32 %c) {
; CHECK-LABEL: define void @_ZTS14example_kernel(
; CHECK-SAME: ptr addrspace(3) [[A:%.*]], ptr addrspace(1) [[B:%.*]], i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(3) [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], [[C]]
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i32, ptr addrspace(3) %a
  %1 = load i32, ptr addrspace(1) %b
  %2 = add i32 %c, %c
  ret void
}

!llvm.module.flags = !{!5}
!nvvm.annotations = !{!0, !1, !0, !2, !2, !2, !2, !3, !3, !2}
!nvvmir.version = !{!4}

!0 = !{null, !"align", i32 8}
!1 = !{null, !"align", i32 8, !"align", i32 65544, !"align", i32 131080}
!2 = !{null, !"align", i32 16}
!3 = !{null, !"align", i32 16, !"align", i32 65552, !"align", i32 131088}
!4 = !{i32 1, i32 4}
!5 = !{i32 1, !"sycl-device", i32 1}
;.
; CHECK: [[META0:![0-9]+]] = !{i32 1, !"sycl-device", i32 1}
; CHECK: [[META1:![0-9]+]] = !{null, !"align", i32 8}
; CHECK: [[META2:![0-9]+]] = !{null, !"align", i32 8, !"align", i32 65544, !"align", i32 131080}
; CHECK: [[META3:![0-9]+]] = !{null, !"align", i32 16}
; CHECK: [[META4:![0-9]+]] = !{null, !"align", i32 16, !"align", i32 65552, !"align", i32 131088}
; CHECK: [[META5:![0-9]+]] = !{i32 1, i32 4}
;.
