; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -p amdgpu-oclc-reflect %s | FileCheck %s -check-prefixes=CHECK,CHECK-SAFE-ATOMICS
; RUN: opt -S -p amdgpu-oclc-reflect -amdgpu-oclc-unsafe-int-atomics=true %s | FileCheck %s -check-prefixes=CHECK,CHECK-UNSAFE-ATOMICS

target triple = "amdgcn-amd-amdhsa"

@.str = private unnamed_addr addrspace(4) constant [31 x i8] c"AMDGPU_OCLC_UNSAFE_INT_ATOMICS\00", align 1

declare hidden i32 @__oclc_amdgpu_reflect(ptr addrspace(4) noundef) local_unnamed_addr

define i32 @foo() {
; CHECK-SAFE-ATOMICS-LABEL: define i32 @foo() {
; CHECK-SAFE-ATOMICS-NEXT:    ret i32 0
;
; CHECK-UNSAFE-ATOMICS-LABEL: define i32 @foo() {
; CHECK-UNSAFE-ATOMICS-NEXT:    ret i32 1
;
  %call = tail call i32 @__oclc_amdgpu_reflect(ptr addrspace(4) noundef @.str)
  ret i32 %call
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
