; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -bugpoint-enable-legacy-pm -localaccessortosharedmemory %s -S -o - | FileCheck %s

target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7"
target triple = "amdgcn-amd-amdhsa"

; This test checks that no transformation is applied when there are no entry points.

define void @_ZTS14example_kernel(ptr addrspace(3) %a, ptr addrspace(1) %b, i32 %c) {
; CHECK-LABEL: define void @_ZTS14example_kernel(
; CHECK-SAME: ptr addrspace(3) [[A:%.*]], ptr addrspace(1) [[B:%.*]], i32 [[C:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(3) [[A]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(1) [[B]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[C]], [[C]]
; CHECK-NEXT:    ret void
;
entry:
  %0 = load i32, ptr addrspace(3) %a
  %1 = load i32, ptr addrspace(1) %b
  %2 = add i32 %c, %c
  ret void
}

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"sycl-device", i32 1}
