//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#define __SPIRV_GENTYPE char
#define __SPIRV_GENTYPE_MANGLED c
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE char2
#define __SPIRV_GENTYPE_MANGLED Dv2_c
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE char4
#define __SPIRV_GENTYPE_MANGLED Dv4_c
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE char8
#define __SPIRV_GENTYPE_MANGLED Dv8_c
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE char16
#define __SPIRV_GENTYPE_MANGLED Dv16_c
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uchar
#define __SPIRV_GENTYPE_MANGLED h
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uchar2
#define __SPIRV_GENTYPE_MANGLED Dv2_h
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uchar4
#define __SPIRV_GENTYPE_MANGLED Dv4_h
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uchar8
#define __SPIRV_GENTYPE_MANGLED Dv8_h
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uchar16
#define __SPIRV_GENTYPE_MANGLED Dv16_h
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE short
#define __SPIRV_GENTYPE_MANGLED s
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE short2
#define __SPIRV_GENTYPE_MANGLED Dv2_s
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE short4
#define __SPIRV_GENTYPE_MANGLED Dv4_s
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE short8
#define __SPIRV_GENTYPE_MANGLED Dv8_s
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE short16
#define __SPIRV_GENTYPE_MANGLED Dv16_s
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ushort
#define __SPIRV_GENTYPE_MANGLED t
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ushort2
#define __SPIRV_GENTYPE_MANGLED Dv2_t
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ushort4
#define __SPIRV_GENTYPE_MANGLED Dv4_t
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ushort8
#define __SPIRV_GENTYPE_MANGLED Dv8_t
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ushort16
#define __SPIRV_GENTYPE_MANGLED Dv16_t
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE int
#define __SPIRV_GENTYPE_MANGLED i
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE int2
#define __SPIRV_GENTYPE_MANGLED Dv2_i
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE int4
#define __SPIRV_GENTYPE_MANGLED Dv4_i
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE int8
#define __SPIRV_GENTYPE_MANGLED Dv8_i
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE int16
#define __SPIRV_GENTYPE_MANGLED Dv16_i
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uint
#define __SPIRV_GENTYPE_MANGLED j
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uint2
#define __SPIRV_GENTYPE_MANGLED Dv2_j
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uint4
#define __SPIRV_GENTYPE_MANGLED Dv4_j
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uint8
#define __SPIRV_GENTYPE_MANGLED Dv8_j
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE uint16
#define __SPIRV_GENTYPE_MANGLED Dv16_j
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE float
#define __SPIRV_GENTYPE_MANGLED f
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE float2
#define __SPIRV_GENTYPE_MANGLED Dv2_f
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE float4
#define __SPIRV_GENTYPE_MANGLED Dv4_f
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE float8
#define __SPIRV_GENTYPE_MANGLED Dv8_f
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE float16
#define __SPIRV_GENTYPE_MANGLED Dv16_f
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE long
#define __SPIRV_GENTYPE_MANGLED l
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE long2
#define __SPIRV_GENTYPE_MANGLED Dv2_l
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE long4
#define __SPIRV_GENTYPE_MANGLED Dv4_l
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE long8
#define __SPIRV_GENTYPE_MANGLED Dv8_l
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE long16
#define __SPIRV_GENTYPE_MANGLED Dv16_l
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ulong
#define __SPIRV_GENTYPE_MANGLED m
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ulong2
#define __SPIRV_GENTYPE_MANGLED Dv2_m
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ulong4
#define __SPIRV_GENTYPE_MANGLED Dv4_m
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ulong8
#define __SPIRV_GENTYPE_MANGLED Dv8_m
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE ulong16
#define __SPIRV_GENTYPE_MANGLED Dv16_m
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#ifdef cl_khr_fp64
#pragma OPENCL EXTENSION cl_khr_fp64 : enable

#define __SPIRV_GENTYPE double
#define __SPIRV_GENTYPE_MANGLED d
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE double2
#define __SPIRV_GENTYPE_MANGLED Dv2_d
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE double4
#define __SPIRV_GENTYPE_MANGLED Dv4_d
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE double8
#define __SPIRV_GENTYPE_MANGLED Dv8_d
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE double16
#define __SPIRV_GENTYPE_MANGLED Dv16_d
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#endif

#ifdef cl_khr_fp16
#pragma OPENCL EXTENSION cl_khr_fp16 : enable

#define __SPIRV_GENTYPE half
#define __SPIRV_GENTYPE_MANGLED Dh
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE half2
#define __SPIRV_GENTYPE_MANGLED Dv2_Dh
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE half4
#define __SPIRV_GENTYPE_MANGLED Dv4_Dh
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE half8
#define __SPIRV_GENTYPE_MANGLED Dv8_Dh
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#define __SPIRV_GENTYPE half16
#define __SPIRV_GENTYPE_MANGLED Dv16_Dh
#include __SPIRV_BODY
#undef __SPIRV_GENTYPE_MANGLED
#undef __SPIRV_GENTYPE

#endif

#undef __SPIRV_BODY
