; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=asan -asan-instrumentation-with-call-threshold=0 -asan-stack=0 -asan-globals=0 -asan-constructor-kind=none -asan-use-after-return=never -S | FileCheck %s

target datalayout = "e-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-n8:16:32:64-G1"
target triple = "spir64-unknown-unknown"

declare dso_local spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 noundef, i32 noundef, i32 noundef, i32 noundef, ptr addrspace(4) noundef, i32 noundef, i32 noundef, i32 noundef, <2 x i32> noundef, ptr addrspace(4) noundef) local_unnamed_addr

declare dso_local spir_func void @_Z33__spirv_Subgroup2DBlockStoreINTELiiiiPKviPviiiDv2_i(i32 noundef, i32 noundef, i32 noundef, i32 noundef, ptr addrspace(4) noundef, ptr addrspace(4) noundef, i32 noundef, i32 noundef, i32 noundef, <2 x i32> noundef) local_unnamed_addr

; Test: Function without sanitize_address should NOT be instrumented
define weak_odr dso_local spir_kernel void @test_block2d_no_sanitize(ptr addrspace(4) %base, ptr addrspace(4) %dst) {
; CHECK-LABEL: define weak_odr dso_local spir_kernel void @test_block2d_no_sanitize(
; CHECK-SAME: ptr addrspace(4) [[BASE:%.*]], ptr addrspace(4) [[DST:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr addrspace(1) null, ptr addrspace(3) @__AsanLaunchInfo, align 8
; CHECK-NEXT:    [[__PRIVATE_BASE:%.*]] = alloca i8, align 1
; CHECK-NEXT:    call void @__asan_set_private_base(ptr [[__PRIVATE_BASE]])
; CHECK-NEXT:    [[COORD:%.*]] = insertelement <2 x i32> poison, i32 0, i64 0
; CHECK-NEXT:    [[COORD1:%.*]] = insertelement <2 x i32> [[COORD]], i32 0, i64 1
; CHECK-NEXT:    call spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 16, i32 32, i32 32, i32 1, ptr addrspace(4) [[BASE]], i32 2047, i32 1023, i32 2047, <2 x i32> [[COORD1]], ptr addrspace(4) [[DST]])
; CHECK-NEXT:    ret void
;
entry:
  %coord = insertelement <2 x i32> poison, i32 0, i64 0
  %coord1 = insertelement <2 x i32> %coord, i32 0, i64 1
  call spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 16, i32 32, i32 32, i32 1, ptr addrspace(4) %base, i32 2047, i32 1023, i32 2047, <2 x i32> %coord1, ptr addrspace(4) %dst)
  ret void
}

; Test: 2D block load should be instrumented with __asan_block2d_load_check
; Function Attrs: sanitize_address
define weak_odr dso_local spir_kernel void @test_block2d_load(ptr addrspace(4) %base, ptr addrspace(4) %dst) #0 {
; CHECK-LABEL: define weak_odr dso_local spir_kernel void @test_block2d_load(
; CHECK-SAME: ptr addrspace(4) [[BASE:%.*]], ptr addrspace(4) [[DST:%.*]], ptr addrspace(1) noundef [[__ASAN_LAUNCH:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr addrspace(1) [[__ASAN_LAUNCH]], ptr addrspace(3) @__AsanLaunchInfo, align 8
; CHECK-NEXT:    [[__PRIVATE_BASE:%.*]] = alloca i8, align 1
; CHECK-NEXT:    call void @__asan_set_private_base(ptr [[__PRIVATE_BASE]])
; CHECK-NEXT:    [[COORD:%.*]] = insertelement <2 x i32> poison, i32 0, i64 0
; CHECK-NEXT:    [[COORD1:%.*]] = insertelement <2 x i32> [[COORD]], i32 0, i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[COORD1]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[COORD1]], i64 1
; CHECK-NEXT:    call void @__asan_block2d_load_check(ptr addrspace(4) [[BASE]], ptr addrspace(4) [[DST]], i32 16, i32 32, i32 32, i32 1, i32 2047, i32 1023, i32 2047, i32 [[TMP0]], i32 [[TMP1]], ptr addrspace(2) null, i32 0, ptr addrspace(2) @__asan_kernel)
; CHECK-NEXT:    call spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 16, i32 32, i32 32, i32 1, ptr addrspace(4) [[BASE]], i32 2047, i32 1023, i32 2047, <2 x i32> [[COORD1]], ptr addrspace(4) [[DST]])
; CHECK-NEXT:    ret void
;
entry:
  %coord = insertelement <2 x i32> poison, i32 0, i64 0
  %coord1 = insertelement <2 x i32> %coord, i32 0, i64 1
  call spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 16, i32 32, i32 32, i32 1, ptr addrspace(4) %base, i32 2047, i32 1023, i32 2047, <2 x i32> %coord1, ptr addrspace(4) %dst)
  ret void
}

; Test: 2D block store should be instrumented with __asan_block2d_store_check
; Function Attrs: sanitize_address
define weak_odr dso_local spir_kernel void @test_block2d_store(ptr addrspace(4) %src, ptr addrspace(4) %base) #0 {
; CHECK-LABEL: define weak_odr dso_local spir_kernel void @test_block2d_store(
; CHECK-SAME: ptr addrspace(4) [[SRC:%.*]], ptr addrspace(4) [[BASE:%.*]], ptr addrspace(1) noundef [[__ASAN_LAUNCH:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr addrspace(1) [[__ASAN_LAUNCH]], ptr addrspace(3) @__AsanLaunchInfo, align 8
; CHECK-NEXT:    [[__PRIVATE_BASE:%.*]] = alloca i8, align 1
; CHECK-NEXT:    call void @__asan_set_private_base(ptr [[__PRIVATE_BASE]])
; CHECK-NEXT:    [[COORD:%.*]] = insertelement <2 x i32> poison, i32 64, i64 0
; CHECK-NEXT:    [[COORD1:%.*]] = insertelement <2 x i32> [[COORD]], i32 128, i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[COORD1]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[COORD1]], i64 1
; CHECK-NEXT:    call void @__asan_block2d_store_check(ptr addrspace(4) [[BASE]], ptr addrspace(4) [[SRC]], i32 16, i32 32, i32 8, i32 1, i32 2047, i32 1023, i32 2047, i32 [[TMP0]], i32 [[TMP1]], ptr addrspace(2) null, i32 0, ptr addrspace(2) @__asan_kernel.1)
; CHECK-NEXT:    call spir_func void @_Z33__spirv_Subgroup2DBlockStoreINTELiiiiPKviPviiiDv2_i(i32 16, i32 32, i32 8, i32 1, ptr addrspace(4) [[SRC]], ptr addrspace(4) [[BASE]], i32 2047, i32 1023, i32 2047, <2 x i32> [[COORD1]])
; CHECK-NEXT:    ret void
;
entry:
  %coord = insertelement <2 x i32> poison, i32 64, i64 0
  %coord1 = insertelement <2 x i32> %coord, i32 128, i64 1
  call spir_func void @_Z33__spirv_Subgroup2DBlockStoreINTELiiiiPKviPviiiDv2_i(i32 16, i32 32, i32 8, i32 1, ptr addrspace(4) %src, ptr addrspace(4) %base, i32 2047, i32 1023, i32 2047, <2 x i32> %coord1)
  ret void
}

; Test: 2D block load with non-zero coords extracts x and y correctly
; Function Attrs: sanitize_address
define weak_odr dso_local spir_kernel void @test_block2d_load_nonzero_coord(ptr addrspace(4) %base, ptr addrspace(4) %dst) #0 {
; CHECK-LABEL: define weak_odr dso_local spir_kernel void @test_block2d_load_nonzero_coord(
; CHECK-SAME: ptr addrspace(4) [[BASE:%.*]], ptr addrspace(4) [[DST:%.*]], ptr addrspace(1) noundef [[__ASAN_LAUNCH:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store ptr addrspace(1) [[__ASAN_LAUNCH]], ptr addrspace(3) @__AsanLaunchInfo, align 8
; CHECK-NEXT:    [[__PRIVATE_BASE:%.*]] = alloca i8, align 1
; CHECK-NEXT:    call void @__asan_set_private_base(ptr [[__PRIVATE_BASE]])
; CHECK-NEXT:    [[COORD:%.*]] = insertelement <2 x i32> poison, i32 16, i64 0
; CHECK-NEXT:    [[COORD1:%.*]] = insertelement <2 x i32> [[COORD]], i32 32, i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[COORD1]], i64 0
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i32> [[COORD1]], i64 1
; CHECK-NEXT:    call void @__asan_block2d_load_check(ptr addrspace(4) [[BASE]], ptr addrspace(4) [[DST]], i32 2, i32 16, i32 32, i32 2, i32 1023, i32 511, i32 1023, i32 [[TMP0]], i32 [[TMP1]], ptr addrspace(2) null, i32 0, ptr addrspace(2) @__asan_kernel.2)
; CHECK-NEXT:    call spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 2, i32 16, i32 32, i32 2, ptr addrspace(4) [[BASE]], i32 1023, i32 511, i32 1023, <2 x i32> [[COORD1]], ptr addrspace(4) [[DST]])
; CHECK-NEXT:    ret void
;
entry:
  %coord = insertelement <2 x i32> poison, i32 16, i64 0
  %coord1 = insertelement <2 x i32> %coord, i32 32, i64 1
  call spir_func void @_Z32__spirv_Subgroup2DBlockLoadINTELiiiiPKviiiDv2_iPv(i32 2, i32 16, i32 32, i32 2, ptr addrspace(4) %base, i32 1023, i32 511, i32 1023, <2 x i32> %coord1, ptr addrspace(4) %dst)
  ret void
}

attributes #0 = { sanitize_address }
