// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --include-generated-funcs --version 5
// RUN: %clang_cc1 -fsycl-is-device -internal-isystem %S/Inputs -triple spir64-unknown-unknown -disable-llvm-passes -emit-llvm %s -o - | FileCheck %s

#include "sycl.hpp"

// CHECK: %struct.__wrapper_class = type { [2 x i32] }
// CHECK: %class.anon = type { [2 x i32] }
// CHECK: %struct.__wrapper_class.0 = type { [2 x ptr addrspace(4)] }
// CHECK: %class.anon.1 = type { [2 x ptr addrspace(4)] }

sycl::queue myQueue;

using namespace sycl;


int main() {
  int Array[2];
  myQueue.submit([&](sycl::handler &h) {
    h.single_task<class IntArray>(
        [=] {
          int local = Array[1];
        });
  });


  int *ArrayOfPointers[2];
  myQueue.submit([&](sycl::handler &h) {
    h.single_task<class PtrArray>(
        [=] {
          int local = *ArrayOfPointers[1];
        });
  });
}
// CHECK-LABEL: define weak_odr spir_kernel void @_ZTSZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_E8IntArray(
// CHECK-SAME: ptr noundef byval([[STRUCT___WRAPPER_CLASS:%.*]]) align 4 [[_ARG_ARRAY:%.*]]) #[[ATTR0:[0-9]+]] comdat !srcloc [[META12:![0-9]+]] !kernel_arg_buffer_location [[META13:![0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[__SYCLKERNEL:%.*]] = alloca [[CLASS_ANON:%.*]], align 4
// CHECK-NEXT:    [[__SYCLKERNEL_ASCAST:%.*]] = addrspacecast ptr [[__SYCLKERNEL]] to ptr addrspace(4)
// CHECK-NEXT:    [[_ARG_ARRAY_ASCAST:%.*]] = addrspacecast ptr [[_ARG_ARRAY]] to ptr addrspace(4)
// CHECK-NEXT:    [[ARRAY:%.*]] = getelementptr inbounds nuw [[CLASS_ANON]], ptr addrspace(4) [[__SYCLKERNEL_ASCAST]], i32 0, i32 0
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw [[STRUCT___WRAPPER_CLASS]], ptr addrspace(4) [[_ARG_ARRAY_ASCAST]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYINIT_BEGIN:%.*]] = getelementptr inbounds [2 x i32], ptr addrspace(4) [[ARRAY]], i64 0, i64 0
// CHECK-NEXT:    br label %[[ARRAYINIT_BODY:.*]]
// CHECK:       [[ARRAYINIT_BODY]]:
// CHECK-NEXT:    [[ARRAYINIT_INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[ARRAYINIT_NEXT:%.*]], %[[ARRAYINIT_BODY]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr addrspace(4) [[ARRAYINIT_BEGIN]], i64 [[ARRAYINIT_INDEX]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [2 x i32], ptr addrspace(4) [[TMP0]], i64 0, i64 [[ARRAYINIT_INDEX]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr addrspace(4) [[ARRAYIDX]], align 4
// CHECK-NEXT:    store i32 [[TMP2]], ptr addrspace(4) [[TMP1]], align 4
// CHECK-NEXT:    [[ARRAYINIT_NEXT]] = add nuw i64 [[ARRAYINIT_INDEX]], 1
// CHECK-NEXT:    [[ARRAYINIT_DONE:%.*]] = icmp eq i64 [[ARRAYINIT_NEXT]], 2
// CHECK-NEXT:    br i1 [[ARRAYINIT_DONE]], label %[[ARRAYINIT_END:.*]], label %[[ARRAYINIT_BODY]]
// CHECK:       [[ARRAYINIT_END]]:
// CHECK-NEXT:    call spir_func void @_ZZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_ENKUlvE_clEv(ptr addrspace(4) noundef align 4 dereferenceable_or_null(8) [[__SYCLKERNEL_ASCAST]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: define internal spir_func void @_ZZZ4mainENKUlRN4sycl3_V17handlerEE_clES2_ENKUlvE_clEv(
// CHECK-SAME: ptr addrspace(4) noundef align 4 dereferenceable_or_null(8) [[THIS:%.*]]) #[[ATTR1:[0-9]+]] align 2 !srcloc [[META12]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr addrspace(4), align 8
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[THIS_ADDR_ASCAST:%.*]] = addrspacecast ptr [[THIS_ADDR]] to ptr addrspace(4)
// CHECK-NEXT:    [[LOCAL_ASCAST:%.*]] = addrspacecast ptr [[LOCAL]] to ptr addrspace(4)
// CHECK-NEXT:    store ptr addrspace(4) [[THIS]], ptr addrspace(4) [[THIS_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[THIS1:%.*]] = load ptr addrspace(4), ptr addrspace(4) [[THIS_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[ARRAY:%.*]] = getelementptr inbounds nuw [[CLASS_ANON:%.*]], ptr addrspace(4) [[THIS1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [2 x i32], ptr addrspace(4) [[ARRAY]], i64 0, i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(4) [[ARRAYIDX]], align 4
// CHECK-NEXT:    store i32 [[TMP0]], ptr addrspace(4) [[LOCAL_ASCAST]], align 4
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: define weak_odr spir_kernel void @_ZTSZZ4mainENKUlRN4sycl3_V17handlerEE0_clES2_E8PtrArray(
// CHECK-SAME: ptr noundef byval([[STRUCT___WRAPPER_CLASS_0:%.*]]) align 8 [[_ARG_ARRAYOFPOINTERS:%.*]]) #[[ATTR0]] comdat !srcloc [[META14:![0-9]+]] !kernel_arg_buffer_location [[META13]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[__SYCLKERNEL:%.*]] = alloca [[CLASS_ANON_1:%.*]], align 8
// CHECK-NEXT:    [[__SYCLKERNEL_ASCAST:%.*]] = addrspacecast ptr [[__SYCLKERNEL]] to ptr addrspace(4)
// CHECK-NEXT:    [[_ARG_ARRAYOFPOINTERS_ASCAST:%.*]] = addrspacecast ptr [[_ARG_ARRAYOFPOINTERS]] to ptr addrspace(4)
// CHECK-NEXT:    [[ARRAYOFPOINTERS:%.*]] = getelementptr inbounds nuw [[CLASS_ANON_1]], ptr addrspace(4) [[__SYCLKERNEL_ASCAST]], i32 0, i32 0
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw [[STRUCT___WRAPPER_CLASS_0]], ptr addrspace(4) [[_ARG_ARRAYOFPOINTERS_ASCAST]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYINIT_BEGIN:%.*]] = getelementptr inbounds [2 x ptr addrspace(4)], ptr addrspace(4) [[ARRAYOFPOINTERS]], i64 0, i64 0
// CHECK-NEXT:    br label %[[ARRAYINIT_BODY:.*]]
// CHECK:       [[ARRAYINIT_BODY]]:
// CHECK-NEXT:    [[ARRAYINIT_INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[ARRAYINIT_NEXT:%.*]], %[[ARRAYINIT_BODY]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds ptr addrspace(4), ptr addrspace(4) [[ARRAYINIT_BEGIN]], i64 [[ARRAYINIT_INDEX]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [2 x ptr addrspace(4)], ptr addrspace(4) [[TMP0]], i64 0, i64 [[ARRAYINIT_INDEX]]
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(4), ptr addrspace(4) [[ARRAYIDX]], align 8
// CHECK-NEXT:    store ptr addrspace(4) [[TMP2]], ptr addrspace(4) [[TMP1]], align 8
// CHECK-NEXT:    [[ARRAYINIT_NEXT]] = add nuw i64 [[ARRAYINIT_INDEX]], 1
// CHECK-NEXT:    [[ARRAYINIT_DONE:%.*]] = icmp eq i64 [[ARRAYINIT_NEXT]], 2
// CHECK-NEXT:    br i1 [[ARRAYINIT_DONE]], label %[[ARRAYINIT_END:.*]], label %[[ARRAYINIT_BODY]]
// CHECK:       [[ARRAYINIT_END]]:
// CHECK-NEXT:    call spir_func void @_ZZZ4mainENKUlRN4sycl3_V17handlerEE0_clES2_ENKUlvE_clEv(ptr addrspace(4) noundef align 8 dereferenceable_or_null(16) [[__SYCLKERNEL_ASCAST]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
//
// CHECK-LABEL: define internal spir_func void @_ZZZ4mainENKUlRN4sycl3_V17handlerEE0_clES2_ENKUlvE_clEv(
// CHECK-SAME: ptr addrspace(4) noundef align 8 dereferenceable_or_null(16) [[THIS:%.*]]) #[[ATTR1]] align 2 !srcloc [[META14]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr addrspace(4), align 8
// CHECK-NEXT:    [[LOCAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[THIS_ADDR_ASCAST:%.*]] = addrspacecast ptr [[THIS_ADDR]] to ptr addrspace(4)
// CHECK-NEXT:    [[LOCAL_ASCAST:%.*]] = addrspacecast ptr [[LOCAL]] to ptr addrspace(4)
// CHECK-NEXT:    store ptr addrspace(4) [[THIS]], ptr addrspace(4) [[THIS_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[THIS1:%.*]] = load ptr addrspace(4), ptr addrspace(4) [[THIS_ADDR_ASCAST]], align 8
// CHECK-NEXT:    [[ARRAYOFPOINTERS:%.*]] = getelementptr inbounds nuw [[CLASS_ANON_1:%.*]], ptr addrspace(4) [[THIS1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [2 x ptr addrspace(4)], ptr addrspace(4) [[ARRAYOFPOINTERS]], i64 0, i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(4), ptr addrspace(4) [[ARRAYIDX]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(4) [[TMP0]], align 4
// CHECK-NEXT:    store i32 [[TMP1]], ptr addrspace(4) [[LOCAL_ASCAST]], align 4
// CHECK-NEXT:    ret void
