// This file attempts to emulate content of a file, which is passed to host
// compiler when integration footer is used: this file is considered to be a
// main file and Inputs/debug-info-checksum.cpp serves as integration footer.
//
// The file is specifically named debug-info-checksum-temp-name.cpp to emulate
// the temporary file name, which is generated by the compiler driver for the
// host .cpp file after appending footer to it.
//
// The command line executed is based on what is actually invoked by the
// compiler driver and we explicitly pass 'Inputs/debug-info-checksum.cpp' as
// a main file name to ensure that we can instruct the compiler to emit the
// correct debug info (paths and checksums), even though the input file is not
// exactly what user specified on the command line.
//
// RUN: %clang_cc1 -fsycl-is-host -I %S %S/Inputs/debug-info-checksum.cpp \
// RUN:   -triple x86_64-unknown-linux-gpu \
// RUN:   -main-file-name "%S/Inputs/debug-info-checksum.cpp" \
// RUN:   -fsycl-use-main-file-name -dwarf-version=5 -S -emit-llvm \
// RUN:   -O0 -debug-info-kind=constructor -o - | FileCheck %s
//
// Verify that DICompileUnit points to a correct file and that checksum is also
// correct.
//
// CHECK: !DICompileUnit({{.*}} file: ![[#FILE:]]
// CHECK: ![[#FILE]] = !DIFile(filename: "{{.*}}clang{{.+}}test{{.+}}CodeGenSYCL{{.+}}Inputs{{.+}}debug-info-checksum.cpp"
// CHECK-SAME: checksumkind: CSK_MD5, checksum: "f1fb5d68350b47d90a53968ac8c40529"

#include "Inputs/debug-info-checksum.cpp
