//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

_CLC_OVERLOAD _CLC_DECL __SPIRV_GENTYPE __spirv_ocl_u_mad24(__SPIRV_GENTYPE x, __SPIRV_GENTYPE y, __SPIRV_GENTYPE z);
