; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -passes=sycl-create-nvvm-annotations -S < %s | FileCheck %s

define void @foo_reqd0() !reqd_work_group_size !6 {
; CHECK-LABEL: define ptx_kernel void @foo_reqd0(
; CHECK-SAME: ) !reqd_work_group_size [[META18:![0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_reqd1() !work_group_num_dim !1 !reqd_work_group_size !4 {
; CHECK-LABEL: define ptx_kernel void @foo_reqd1(
; CHECK-SAME: ) !reqd_work_group_size [[META19:![0-9]+]] !work_group_num_dim [[META20:![0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_reqd2() !work_group_num_dim !2 !reqd_work_group_size !5 {
; CHECK-LABEL: define ptx_kernel void @foo_reqd2(
; CHECK-SAME: ) !reqd_work_group_size [[META21:![0-9]+]] !work_group_num_dim [[META22:![0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_reqd3() !work_group_num_dim !3 !reqd_work_group_size !6 {
; CHECK-LABEL: define ptx_kernel void @foo_reqd3(
; CHECK-SAME: ) !reqd_work_group_size [[META18]] !work_group_num_dim [[META23:![0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

; Check that padding is ignored: we should only read the first dimension of the
; 3D metadata
define void @foo_reqd4() !work_group_num_dim !1 !reqd_work_group_size !6 {
; CHECK-LABEL: define ptx_kernel void @foo_reqd4(
; CHECK-SAME: ) !reqd_work_group_size [[META18]] !work_group_num_dim [[META20]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_max0() !work_group_num_dim !1 !max_work_group_size !6 {
; CHECK-LABEL: define ptx_kernel void @foo_max0(
; CHECK-SAME: ) !work_group_num_dim [[META20]] !max_work_group_size [[META18]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_max1() !work_group_num_dim !2 !max_work_group_size !6 {
; CHECK-LABEL: define ptx_kernel void @foo_max1(
; CHECK-SAME: ) !work_group_num_dim [[META22]] !max_work_group_size [[META18]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_max2() !work_group_num_dim !3 !max_work_group_size !6 {
; CHECK-LABEL: define ptx_kernel void @foo_max2(
; CHECK-SAME: ) !work_group_num_dim [[META23]] !max_work_group_size [[META18]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_minwgpercu0() !min_work_groups_per_cu !2 {
; CHECK-LABEL: define ptx_kernel void @foo_minwgpercu0(
; CHECK-SAME: ) !min_work_groups_per_cu [[META22]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @foo_maxwgpermp() !max_work_groups_per_mp !3 {
; CHECK-LABEL: define ptx_kernel void @foo_maxwgpermp(
; CHECK-SAME: ) !max_work_groups_per_mp [[META23]] {
; CHECK-NEXT:    ret void
;
  ret void
}

!1 = !{i32 1}
!2 = !{i32 2}
!3 = !{i32 3}

!4 = !{i32 4}
!5 = !{i32 4, i32 8}
!6 = !{i32 4, i32 8, i32 16}

;.
; CHECK: [[META0:![0-9]+]] = !{ptr @foo_reqd0, !"reqntidx", i32 4}
; CHECK: [[META1:![0-9]+]] = !{ptr @foo_reqd0, !"reqntidy", i32 8}
; CHECK: [[META2:![0-9]+]] = !{ptr @foo_reqd0, !"reqntidx", i32 16}
; CHECK: [[META3:![0-9]+]] = !{ptr @foo_reqd1, !"reqntidx", i32 4}
; CHECK: [[META4:![0-9]+]] = !{ptr @foo_reqd2, !"reqntidx", i32 4}
; CHECK: [[META5:![0-9]+]] = !{ptr @foo_reqd2, !"reqntidy", i32 8}
; CHECK: [[META6:![0-9]+]] = !{ptr @foo_reqd3, !"reqntidx", i32 4}
; CHECK: [[META7:![0-9]+]] = !{ptr @foo_reqd3, !"reqntidy", i32 8}
; CHECK: [[META8:![0-9]+]] = !{ptr @foo_reqd3, !"reqntidx", i32 16}
; CHECK: [[META9:![0-9]+]] = !{ptr @foo_reqd4, !"reqntidx", i32 4}
; CHECK: [[META10:![0-9]+]] = !{ptr @foo_max0, !"maxntidx", i32 4}
; CHECK: [[META11:![0-9]+]] = !{ptr @foo_max1, !"maxntidx", i32 4}
; CHECK: [[META12:![0-9]+]] = !{ptr @foo_max1, !"maxntidy", i32 8}
; CHECK: [[META13:![0-9]+]] = !{ptr @foo_max2, !"maxntidx", i32 4}
; CHECK: [[META14:![0-9]+]] = !{ptr @foo_max2, !"maxntidy", i32 8}
; CHECK: [[META15:![0-9]+]] = !{ptr @foo_max2, !"maxntidz", i32 16}
; CHECK: [[META16:![0-9]+]] = !{ptr @foo_minwgpercu0, !"minctasm", i32 2}
; CHECK: [[META17:![0-9]+]] = !{ptr @foo_maxwgpermp, !"maxclusterrank", i32 3}
; CHECK: [[META18]] = !{i32 4, i32 8, i32 16}
; CHECK: [[META19]] = !{i32 4}
; CHECK: [[META20]] = !{i32 1}
; CHECK: [[META21]] = !{i32 4, i32 8}
; CHECK: [[META22]] = !{i32 2}
; CHECK: [[META23]] = !{i32 3}
;.
