name: 'Build Docker container'
description: 'Build Docker container in a standard way'

inputs:
  build-args:
    description: "List of build-time variables"
    required: false
  tags:
    description: "List of tags"
    required: true
  push:
    description: "Whether to push Docker image or not"
    required: false
    default: false
  username:
    description: "Registry user name"
    required: true
  password:
    description: "Registry user password"
    required: true
  file:
    description: "Dockerfile"
    required: true

runs:
  using: "composite"
  steps:
  - name: Login to GitHub Container Registry
    uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
    with:
      registry: ghcr.io
      username: ${{ inputs.username }}
      password: ${{ inputs.password }}
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
  - name: Build and Push Container
    uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
    with:
      push: ${{ inputs.push }}
      tags: ${{ inputs.tags }}
      build-args: ${{ inputs.build-args }}
      context: ${{ github.workspace }}/devops
      file: ${{ github.workspace }}/devops/containers/${{ inputs.file }}.Dockerfile
      secrets: |
        github_token=${{ github.token }}
