"""Parse JUnit XML test results."""
import sys
from pathlib import Path
from typing import List, NamedTuple, Optional

import defusedxml.ElementTree as ET

from ..constants import TEST_NOT_SELECTED_MSG


class ParsedXMLTests(NamedTuple):
    """Result of XML test parsing.

    Attributes:
        skipped: Tests with <skipped> element (excluding 'Test not selected').
        excluded: Tests with 'Test not selected' message (from LIT_FILTER_OUT).
    """
    skipped: List[str]
    excluded: List[str]


def _format_test_name(classname: str, name: str) -> str:
    """Format test name from XML attributes.

    Args:
        classname: Test class name.
        name: Test name.

    Returns:
        Formatted test name (classname.name if both present, otherwise just name).
    """
    if classname and name:
        return f"{classname}.{name}"
    return name


class JUnitXMLParser:
    """Parse JUnit XML format (from LIT --xunit-xml-output).

    This parser extracts test information from XML files generated by
    LLVM LIT's --xunit-xml-output option.
    """

    def __init__(self, xml_path: Optional[str]):
        """Initialize parser with XML file path.

        Args:
            xml_path: Path to XML file, or None/empty string.
        """
        self.xml_path = xml_path
        self._root = None

    def parse(self) -> bool:
        """Parse XML file safely.

        Returns:
            True if parsing succeeded, False otherwise.
        """
        if not self.xml_path:
            return False

        if not Path(self.xml_path).exists():
            print(
                f"Note: XML file not found: {self.xml_path}",
                file=sys.stderr
            )
            return False

        try:
            tree = ET.parse(self.xml_path)
            self._root = tree.getroot()
            return True
        except ET.ParseError as e:
            print(
                f"Warning: Failed to parse XML file {self.xml_path}: {e}",
                file=sys.stderr
            )
            return False
        except (OSError, ValueError) as e:
            print(
                f"Warning: Error reading XML file {self.xml_path}: {e}",
                file=sys.stderr
            )
            return False

    def extract_tests_from_xml(self) -> ParsedXMLTests:
        """Extract skipped and excluded tests from LIT xunit XML.

        Parses XML once and separates tests into two categories:
        - Skipped: tests with <skipped> element (excluding 'Test not selected')
        - Excluded: tests with 'Test not selected' message (from LIT_FILTER_OUT)

        Returns:
            ParsedXMLTests with skipped_tests and excluded_tests lists.
        """
        if not self.parse():
            return ParsedXMLTests([], [])

        skipped = []
        excluded = []

        for testcase in self._root.findall(".//testcase"):
            skipped_elem = testcase.find("skipped")
            if skipped_elem is None:
                continue

            message = skipped_elem.get("message", "")
            test_name = _format_test_name(
                testcase.get("classname", ""), testcase.get("name", "")
            )

            if not test_name:
                continue

            # Separate by message type
            if TEST_NOT_SELECTED_MSG in message:
                excluded.append(test_name)
            else:
                skipped.append(test_name)

        if skipped:
            print(
                f"Note: Found {len(skipped)} skipped tests in "
                f"XML: {self.xml_path}",
                file=sys.stderr,
            )
        if excluded:
            print(
                f"Note: Found {len(excluded)} excluded tests in "
                f"XML: {self.xml_path}",
                file=sys.stderr,
            )

        return ParsedXMLTests(skipped=skipped, excluded=excluded)

    def extract_skipped_tests(self) -> List[str]:
        """Extract only skipped tests (excluding 'Test not selected').

        Returns:
            List of skipped test names.
        """
        skipped, _ = self.extract_tests_from_xml()
        return skipped

    def extract_excluded_tests(self) -> List[str]:
        """Extract only excluded tests ('Test not selected').

        Returns:
            List of excluded test names.
        """
        _, excluded = self.extract_tests_from_xml()
        return excluded


# Standalone function for backward compatibility
def extract_tests_from_xml(xml_path: str) -> ParsedXMLTests:
    """Extract skipped and excluded tests from LIT xunit XML.

    This is a convenience function that creates a parser and extracts tests.
    For new code, prefer using JUnitXMLParser class directly.

    Args:
        xml_path: Path to XML file.

    Returns:
        ParsedXMLTests with skipped_tests and excluded_tests lists.
    """
    parser = JUnitXMLParser(xml_path)
    return parser.extract_tests_from_xml()
