// Copyright (C) Codeplay Software Limited
//
// Licensed under the Apache License, Version 2.0 (the "License") with LLVM
// Exceptions; you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/LICENSE.txt
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations
// under the License.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

/// @file
///
/// @brief Transform the pattern generated by ternary operators to a
/// vectorizable instruction set

#ifndef VECZ_TRANSFORM_TERNARY_TRANSFORM_PASS_H_INCLUDED
#define VECZ_TRANSFORM_TERNARY_TRANSFORM_PASS_H_INCLUDED

#include <llvm/IR/PassManager.h>

namespace vecz {

/// @brief This pass tries to transform selects with pointer operands,
/// transforms to individual GEPs followed by masked memory operations.
class TernaryTransformPass : public llvm::PassInfoMixin<TernaryTransformPass> {
 public:
  TernaryTransformPass() = default;

  /// @brief The entry point to the pass.
  //
  /// @param[in] F Function to optimize.
  /// @param[in] AM FunctionAnalysisManager providing analyses.
  //
  /// @return The preserved analyses.
  llvm::PreservedAnalyses run(llvm::Function &F,
                              llvm::FunctionAnalysisManager &AM);

  // @brief Pass name.
  static llvm::StringRef name() { return "Ternary transform pass"; }
};
}  // namespace vecz

#endif  // VECZ_TRANSFORM_TERNARY_TRANSFORM_PASS_H_INCLUDED
