= SYCL Proposals: Level Zero Backend: Free Memory Device Query
James Brodman <james.brodman@intel.com>
v0.1
:source-highlighter: pygments
:icons: font
== Introduction
This document presents an addition for the Level Zero Backend Specification.  The goal of this proposal is to give users the ability to query the amount of currently free memory on a device that uses a Level Zero Backend in SYCL 2020.

== Free Memory query
Level Zero contains a library for system resource management called Sysman.  Sysman allows programmers to query the amount of free, or unallocated, memory in a device.  This extension provides a new device information descriptor specific to Level Zero Backends that allows DPC++ programs to query the amount of free memory for a given device. The new descriptor is as follows: 

.Proposed Backend Device Information Descriptor
[source,c++]
----
namespace sycl{
namespace ext {
namespace oneapi{
namespace level_zero {
namespace info {
namespace device {

struct free_memory {
    using return_type = uint64_t;
};

} // namespace device;
} // namespace info
} // namespace level_zero
} // namespace oneapi
} // namespace ext
} // namespace sycl
----

The new struct `free_memory` is used in conjuction with the `get_backend_info()` method of the `device` class in SYCL 2020.  The query will return the number of bytes of free memory for that device.

.Example Usage
[source,c++]
----
sycl::queue Queue;
auto Device = Queue.get_device();

uint64_t freeMemory = Device.get_backend_info<sycl::ext::oneapi::info::device::free_memory>();
----
