; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature
; RUN: opt < %s -passes=deadargelim -S | FileCheck %s
; RUN: opt < %s -passes=deadargelim-sycl -S | FileCheck %s

target triple = "spir64"

; This test ensures dead arguments are not eliminated
; from a global function that is not a SPIR kernel.

; CHECK-NOT:    !sycl_kernel_omit_args

define weak_odr void @NotASpirKernel(float %arg1, float %arg2) {
; CHECK-LABEL: define {{[^@]+}}@NotASpirKernel
; CHECK-SAME: (float [[ARG1:%.*]], float [[ARG2:%.*]]) {
; CHECK-NEXT:    call void @foo(float [[ARG1]])
; CHECK-NEXT:    ret void
;
  call void @foo(float %arg1)
  ret void
}

; This test ensures dead arguments are not eliminated
; from an ESIMD kernel.

define weak_odr void @ESIMDKernel(float %arg1, float %arg2) !sycl_explicit_simd !0 {
; CHECK-LABEL: define {{[^@]+}}@ESIMDKernel
; CHECK-SAME: (float [[ARG1:%.*]], float [[ARG2:%.*]]) {{.*}}{
; CHECK-NEXT:    call void @foo(float [[ARG1]])
; CHECK-NEXT:    ret void
;
  call void @foo(float %arg1)
  ret void
}

; The following two tests ensure that dead arguments are not eliminated
; from a free function kernel.

define weak_odr spir_kernel void @FreeFuncKernelSingleTask(float %arg1, float %arg2) "sycl-single-task-kernel"="0" {
; CHECK-LABEL: define {{[^@]+}}@FreeFuncKernelSingleTask
; CHECK-SAME: (float [[ARG1:%.*]], float [[ARG2:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    call void @foo(float [[ARG1]])
; CHECK-NEXT:    ret void
;
  call void @foo(float %arg1)
  ret void
}

define weak_odr spir_kernel void @FreeFuncKernelNdRange(float %arg1, float %arg2) "sycl-nd-range-kernel"="0" {
; CHECK-LABEL: define {{[^@]+}}@FreeFuncKernelNdRange
; CHECK-SAME: (float [[ARG1:%.*]], float [[ARG2:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    call void @foo(float [[ARG1]])
; CHECK-NEXT:    ret void
;
  call void @foo(float %arg1)
  ret void
}

declare void @foo(float %arg)

!0 = !{}
