= SYCL Proposals: Queue Order Properties
James Brodman <james.brodman@intel.com>
v0.2
:source-highlighter: pygments
:icons: font
== Introduction
This document presents an addition proposed for a future version of the SYCL Specification.  The goal of this proposal is to reduce the complexity and verbosity of using SYCL for programmers.

== Queue Order Properties
Queues in SYCL are out-of-order by default.  SYCL constructs directed acyclic graphs to ensure tasks are properly ordered based on their data dependences.  However, many programs only require linear DAGs.  The overheads of constructing and managing DAGs are unnecessary for this class of program.  The `in_order` and `out_of_order` queue properties are proposed to serve this class of programs by providing simple programmer-specified semantics.  These properties are used with the existing `property_list` mechanism that is part of the normal SYCL `queue`.  

Creating a queue without any property is equivalent to creating a queue with the `out_of_order` property.

.Proposed Queue Properties
[cols="^50,50",options="header"]
|===

|Property |Description
|`property::queue::in_order`
| The `in_order` property adds the requirement that the SYCL queue provides in-order semantics where tasks are executed in the order in which they are submitted. Tasks submitted in this fashion can be viewed as having an implicit dependence on the previously submitted operation.

|`property::queue::out_of_order`
| The `out_of_order` property adds the requirement that the SYCL queue provides out-of-order semantics that are found by default in SYCL queues.  
|===



