= SYCL Proposals: Queue Order Properties
James Brodman <james.brodman@intel.com>
v0.2
:source-highlighter: pygments
:icons: font
== Introduction
This document presents an addition proposed for a future version of the SYCL Specification.  The goal of this proposal is to reduce the complexity and verbosity of using SYCL for programmers.

== Queue Order Properties
Queues in SYCL are out-of-order by default.  SYCL constructs directed acyclic graphs to ensure tasks are properly ordered based on their data dependences.  However, many programs only require linear DAGs.  The overheads of constructing and managing DAGs are unnecessary for this class of program.  The `in_order` queue property is proposed to serve this class of programs by providing programmer-specified in-order semantics.  This property is used with the existing `property_list` mechanism that is part of the normal SYCL `queue`.  

.Proposed Queue Property
[cols="^50,50",options="header"]
|===

|Property |Description
|`property::queue::in_order`
| The `in_order` property adds the requirement that the SYCL queue provides in-order semantics where tasks are executed in the order in which they are submitted. Tasks submitted in this fashion can be viewed as having an implicit dependence on the previously submitted operation.
|===

.Proposed Queue Method Addition
[cols="^25,^25,50",options="header"]
|===

|Method |Return Type |Description
|`is_in_order()`
|`bool`
| Returns `true` if a SYCL `queue` was created with the `in_order` property.  Equivalent to `has_property<property::queue::in_order>()`.
|===


