// Use update_test.sh to (re-)generate the checks
// REQUIRES: linux
// RUN: bash %S/deps_known.sh sycl/khr/includes/images.hpp | FileCheck %s

// CHECK-LABEL: Dependencies for <sycl/khr/includes/images.hpp>:
// CHECK-NEXT: /dev/null: /dev/null
// CHECK-NEXT: khr/includes/images.hpp
// CHECK-NEXT: khr/includes/version.hpp
// CHECK-NEXT: detail/defines_elementary.hpp
// CHECK-NEXT: feature_test.hpp
// CHECK-NEXT: accessor_image.hpp
// CHECK-NEXT: accessor.hpp
// CHECK-NEXT: access/access.hpp
// CHECK-NEXT: buffer.hpp
// CHECK-NEXT: backend_types.hpp
// CHECK-NEXT: detail/array.hpp
// CHECK-NEXT: detail/common.hpp
// CHECK-NEXT: detail/export.hpp
// CHECK-NEXT: __spirv/spirv_vars.hpp
// CHECK-NEXT: detail/fwd/accessor.hpp
// CHECK-NEXT: detail/defines.hpp
// CHECK-NEXT: detail/helpers.hpp
// CHECK-NEXT: __spirv/spirv_types.hpp
// CHECK-NEXT: memory_enums.hpp
// CHECK-NEXT: detail/iostream_proxy.hpp
// CHECK-NEXT: detail/is_device_copyable.hpp
// CHECK-NEXT: detail/owner_less_base.hpp
// CHECK-NEXT: detail/impl_utils.hpp
// CHECK-NEXT: ext/oneapi/weak_object_base.hpp
// CHECK-NEXT: detail/property_helper.hpp
// CHECK-NEXT: detail/stl_type_traits.hpp
// CHECK-NEXT: detail/sycl_mem_obj_allocator.hpp
// CHECK-NEXT: detail/aligned_allocator.hpp
// CHECK-NEXT: detail/os_util.hpp
// CHECK-NEXT: ext/oneapi/accessor_property_list.hpp
// CHECK-NEXT: detail/property_list_base.hpp
// CHECK-NEXT: exception.hpp
// CHECK-NEXT: detail/string.hpp
// CHECK-NEXT: property_list.hpp
// CHECK-NEXT: properties/property_traits.hpp
// CHECK-NEXT: id.hpp
// CHECK-NEXT: range.hpp
// CHECK-NEXT: ur_api.h
// CHECK-NEXT: detail/accessor_iterator.hpp
// CHECK-NEXT: detail/generic_type_traits.hpp
// CHECK-NEXT: aliases.hpp
// CHECK-NEXT: bit_cast.hpp
// CHECK-NEXT: detail/fwd/half.hpp
// CHECK-NEXT: detail/type_traits.hpp
// CHECK-NEXT: detail/type_traits/vec_marray_traits.hpp
// CHECK-NEXT: detail/fwd/multi_ptr.hpp
// CHECK-NEXT: detail/handler_proxy.hpp
// CHECK-NEXT: multi_ptr.hpp
// CHECK-NEXT: detail/address_space_cast.hpp
// CHECK-NEXT: pointers.hpp
// CHECK-NEXT: properties/accessor_properties.hpp
// CHECK-NEXT: properties/runtime_accessor_properties.def
// CHECK-NEXT: properties/buffer_properties.hpp
// CHECK-NEXT: context.hpp
// CHECK-NEXT: async_handler.hpp
// CHECK-NEXT: detail/info_desc_helpers.hpp
// CHECK-NEXT: aspects.hpp
// CHECK-NEXT: info/aspects.def
// CHECK-NEXT: info/aspects_deprecated.def
// CHECK-NEXT: info/info_desc.hpp
// CHECK-NEXT: ext/oneapi/experimental/device_architecture.hpp
// CHECK-NEXT: ext/oneapi/experimental/device_architecture.def
// CHECK-NEXT: ext/oneapi/experimental/forward_progress.hpp
// CHECK-NEXT: ext/oneapi/matrix/query-types.hpp
// CHECK-NEXT: ext/oneapi/bfloat16.hpp
// CHECK-NEXT: half_type.hpp
// CHECK-NEXT: ext/oneapi/matrix/matrix-unified-utils.hpp
// CHECK-NEXT: info/platform_traits.def
// CHECK-NEXT: info/context_traits.def
// CHECK-NEXT: info/device_traits_2020_deprecated.def
// CHECK-NEXT: info/device_traits_deprecated.def
// CHECK-NEXT: info/device_traits.def
// CHECK-NEXT: info/queue_traits.def
// CHECK-NEXT: info/kernel_traits.def
// CHECK-NEXT: info/kernel_device_specific_traits.def
// CHECK-NEXT: info/event_traits.def
// CHECK-NEXT: info/event_profiling_traits.def
// CHECK-NEXT: info/ext_codeplay_device_traits.def
// CHECK-NEXT: info/ext_intel_device_traits.def
// CHECK-NEXT: info/ext_intel_kernel_info_traits.def
// CHECK-NEXT: info/ext_oneapi_device_traits.def
// CHECK-NEXT: info/ext_oneapi_kernel_queue_specific_traits.def
// CHECK-NEXT: usm/usm_enums.hpp
// CHECK-NEXT: properties/buffer_properties.def
// CHECK-NEXT: detail/image_accessor_util.hpp
// CHECK-NEXT: device.hpp
// CHECK-NEXT: detail/string_view.hpp
// CHECK-NEXT: detail/util.hpp
// CHECK-NEXT: device_selector.hpp
// CHECK-NEXT: kernel_bundle_enums.hpp
// CHECK-NEXT: image.hpp
// CHECK-NEXT: detail/backend_traits.hpp
// CHECK-NEXT: event.hpp
// CHECK-NEXT: sampler.hpp
// CHECK-NEXT: vector.hpp
// CHECK-NEXT: detail/named_swizzles_mixin.hpp
// CHECK-NEXT: detail/vector_arith.hpp
// CHECK-NEXT: detail/memcpy.hpp
// CHECK-NEXT: detail/image_ocl_types.hpp
// CHECK-NEXT: __spirv/spirv_ops.hpp
// CHECK-NEXT: properties/image_properties.hpp
// CHECK-NEXT: properties/image_properties.def
// CHECK-EMPTY:
