// Use update_test.sh to (re-)generate the checks
// REQUIRES: linux
// RUN: bash %S/deps_known.sh sycl/detail/core.hpp | FileCheck %s

// CHECK-LABEL: Dependencies for <sycl/detail/core.hpp>:
// CHECK-NEXT: /dev/null: /dev/null
// CHECK-NEXT: detail/core.hpp
// CHECK-NEXT: accessor.hpp
// CHECK-NEXT: access/access.hpp
// CHECK-NEXT: detail/defines_elementary.hpp
// CHECK-NEXT: CL/__spirv/spirv_ops.hpp
// CHECK-NEXT: CL/__spirv/spirv_types.hpp
// CHECK-NEXT: detail/defines.hpp
// CHECK-NEXT: detail/export.hpp
// CHECK-NEXT: aliases.hpp
// CHECK-NEXT: half_type.hpp
// CHECK-NEXT: bit_cast.hpp
// CHECK-NEXT: detail/iostream_proxy.hpp
// CHECK-NEXT: detail/vector_traits.hpp
// CHECK-NEXT: aspects.hpp
// CHECK-NEXT: info/aspects.def
// CHECK-NEXT: info/aspects_deprecated.def
// CHECK-NEXT: atomic.hpp
// CHECK-NEXT: detail/helpers.hpp
// CHECK-NEXT: detail/pi.hpp
// CHECK-NEXT: backend_types.hpp
// CHECK-NEXT: detail/os_util.hpp
// CHECK-NEXT: detail/pi.h
// CHECK-NEXT: detail/pi_error.def
// CHECK-NEXT: detail/pi.def
// CHECK-NEXT: memory_enums.hpp
// CHECK-NEXT: CL/__spirv/spirv_vars.hpp
// CHECK-NEXT: multi_ptr.hpp
// CHECK-NEXT: detail/type_traits.hpp
// CHECK-NEXT: detail/generic_type_lists.hpp
// CHECK-NEXT: detail/type_list.hpp
// CHECK-NEXT: detail/boost/mp11/algorithm.hpp
// CHECK-NEXT: detail/boost/mp11/list.hpp
// CHECK-NEXT: detail/boost/mp11/integral.hpp
// CHECK-NEXT: detail/boost/mp11/version.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_value.hpp
// CHECK-NEXT: detail/boost/mp11/detail/config.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_list.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_list_v.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_is_list.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_is_value_list.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_front.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_rename.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_defer.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_append.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_count.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_plus.hpp
// CHECK-NEXT: detail/boost/mp11/utility.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_fold.hpp
// CHECK-NEXT: detail/boost/mp11/set.hpp
// CHECK-NEXT: detail/boost/mp11/function.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_min_element.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_void.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_copy_if.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_remove_if.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_map_find.hpp
// CHECK-NEXT: detail/boost/mp11/detail/mp_with_index.hpp
// CHECK-NEXT: detail/boost/mp11/integer_sequence.hpp
// CHECK-NEXT: buffer.hpp
// CHECK-NEXT: context.hpp
// CHECK-NEXT: async_handler.hpp
// CHECK-NEXT: detail/info_desc_helpers.hpp
// CHECK-NEXT: id.hpp
// CHECK-NEXT: detail/array.hpp
// CHECK-NEXT: exception.hpp
// CHECK-NEXT: detail/cl.h
// CHECK-NEXT: CL/cl.h
// CHECK-NEXT: CL/cl_version.h
// CHECK-NEXT: CL/cl_platform.h
// CHECK-NEXT: CL/cl_ext.h
// CHECK-NEXT: detail/common.hpp
// CHECK-NEXT: range.hpp
// CHECK-NEXT: info/info_desc.hpp
// CHECK-NEXT: ext/oneapi/experimental/device_architecture.hpp
// CHECK-NEXT: ext/oneapi/experimental/architectures.def
// CHECK-NEXT: ext/oneapi/experimental/forward_progress.hpp
// CHECK-NEXT: ext/oneapi/matrix/query-types.hpp
// CHECK-NEXT: ext/oneapi/bfloat16.hpp
// CHECK-NEXT: ext/oneapi/matrix/matrix-unified-utils.hpp
// CHECK-NEXT: info/platform_traits.def
// CHECK-NEXT: info/context_traits.def
// CHECK-NEXT: info/device_traits_deprecated.def
// CHECK-NEXT: info/device_traits.def
// CHECK-NEXT: info/queue_traits.def
// CHECK-NEXT: info/kernel_traits.def
// CHECK-NEXT: info/kernel_device_specific_traits.def
// CHECK-NEXT: info/event_traits.def
// CHECK-NEXT: info/event_profiling_traits.def
// CHECK-NEXT: info/ext_codeplay_device_traits.def
// CHECK-NEXT: info/ext_intel_device_traits.def
// CHECK-NEXT: info/ext_oneapi_device_traits.def
// CHECK-NEXT: info/sycl_backend_traits.def
// CHECK-NEXT: detail/owner_less_base.hpp
// CHECK-NEXT: detail/impl_utils.hpp
// CHECK-NEXT: ext/oneapi/weak_object_base.hpp
// CHECK-NEXT: platform.hpp
// CHECK-NEXT: detail/string.hpp
// CHECK-NEXT: detail/string_view.hpp
// CHECK-NEXT: detail/util.hpp
// CHECK-NEXT: device_selector.hpp
// CHECK-NEXT: property_list.hpp
// CHECK-NEXT: detail/property_helper.hpp
// CHECK-NEXT: detail/property_list_base.hpp
// CHECK-NEXT: properties/property_traits.hpp
// CHECK-NEXT: detail/is_device_copyable.hpp
// CHECK-NEXT: detail/stl_type_traits.hpp
// CHECK-NEXT: detail/sycl_mem_obj_allocator.hpp
// CHECK-NEXT: detail/aligned_allocator.hpp
// CHECK-NEXT: event.hpp
// CHECK-NEXT: ext/oneapi/accessor_property_list.hpp
// CHECK-NEXT: detail/accessor_iterator.hpp
// CHECK-NEXT: detail/generic_type_traits.hpp
// CHECK-NEXT: detail/handler_proxy.hpp
// CHECK-NEXT: pointers.hpp
// CHECK-NEXT: properties/accessor_properties.hpp
// CHECK-NEXT: properties/buffer_properties.hpp
// CHECK-NEXT: sampler.hpp
// CHECK-NEXT: queue.hpp
// CHECK-NEXT: detail/assert_happened.hpp
// CHECK-NEXT: detail/cg_types.hpp
// CHECK-NEXT: detail/host_profiling_info.hpp
// CHECK-NEXT: detail/item_base.hpp
// CHECK-NEXT: detail/kernel_desc.hpp
// CHECK-NEXT: group.hpp
// CHECK-NEXT: device_event.hpp
// CHECK-NEXT: h_item.hpp
// CHECK-NEXT: item.hpp
// CHECK-NEXT: kernel_handler.hpp
// CHECK-NEXT: nd_item.hpp
// CHECK-NEXT: nd_range.hpp
// CHECK-NEXT: sub_group.hpp
// CHECK-NEXT: ext/oneapi/functional.hpp
// CHECK-NEXT: detail/spirv.hpp
// CHECK-NEXT: ext/oneapi/experimental/non_uniform_groups.hpp
// CHECK-NEXT: ext/oneapi/sub_group_mask.hpp
// CHECK-NEXT: builtins.hpp
// CHECK-NEXT: detail/builtins/builtins.hpp
// CHECK-NEXT: builtins_utils_vec.hpp
// CHECK-NEXT: builtins_utils_scalar.hpp
// CHECK-NEXT: detail/boolean.hpp
// CHECK-NEXT: marray.hpp
// CHECK-NEXT: types.hpp
// CHECK-NEXT: vector.hpp
// CHECK-NEXT: detail/memcpy.hpp
// CHECK-NEXT: detail/vector_convert.hpp
// CHECK-NEXT: swizzles.def
// CHECK-NEXT: detail/builtins/common_functions.inc
// CHECK-NEXT: detail/builtins/helper_macros.hpp
// CHECK-NEXT: detail/builtins/geometric_functions.inc
// CHECK-NEXT: detail/builtins/half_precision_math_functions.inc
// CHECK-NEXT: detail/builtins/integer_functions.inc
// CHECK-NEXT: detail/builtins/math_functions.inc
// CHECK-NEXT: detail/builtins/native_math_functions.inc
// CHECK-NEXT: detail/builtins/relational_functions.inc
// CHECK-NEXT: feature_test.hpp
// CHECK-NEXT: functional.hpp
// CHECK-NEXT: device.hpp
// CHECK-NEXT: kernel_bundle_enums.hpp
// CHECK-NEXT: exception_list.hpp
// CHECK-NEXT: ext/oneapi/device_global/device_global.hpp
// CHECK-NEXT: ext/oneapi/device_global/properties.hpp
// CHECK-NEXT: ext/oneapi/properties/property.hpp
// CHECK-NEXT: ext/oneapi/properties/property_value.hpp
// CHECK-NEXT: ext/oneapi/properties/property_utils.hpp
// CHECK-NEXT: ext/oneapi/properties/properties.hpp
// CHECK-NEXT: ext/oneapi/experimental/graph.hpp
// CHECK-NEXT: handler.hpp
// CHECK-NEXT: detail/cg.hpp
// CHECK-NEXT: kernel.hpp
// CHECK-NEXT: kernel_bundle.hpp
// CHECK-NEXT: detail/reduction_forward.hpp
// CHECK-NEXT: ext/intel/experimental/fp_control_kernel_properties.hpp
// CHECK-NEXT: ext/intel/experimental/kernel_execution_properties.hpp
// CHECK-NEXT: ext/oneapi/bindless_images_interop.hpp
// CHECK-NEXT: ext/oneapi/bindless_images_mem_handle.hpp
// CHECK-NEXT: ext/oneapi/experimental/use_root_sync_prop.hpp
// CHECK-NEXT: ext/oneapi/experimental/virtual_functions.hpp
// CHECK-NEXT: ext/oneapi/kernel_properties/properties.hpp
// CHECK-EMPTY:
