; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=sycl-optimize-barriers -S < %s | FileCheck %s

; Test that multiple dominating global barriers combine semantics and later barriers are downgraded.

@glob = external addrspace(1) global i32

define spir_kernel void @multi_series() {
; CHECK-LABEL: define spir_kernel void @multi_series() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    store i32 0, ptr addrspace(1) @glob, align 4
; CHECK-NEXT:    call void @_Z22__spirv_ControlBarrieriii(i32 noundef 1, i32 noundef 1, i32 noundef 520)
; CHECK-NEXT:    ret void
;
entry:
  store i32 0, ptr addrspace(1) @glob, align 4
  call void @_Z22__spirv_ControlBarrieriii(i32 noundef 1, i32 noundef 1, i32 noundef 514)
  call void @_Z22__spirv_ControlBarrieriii(i32 noundef 1, i32 noundef 1, i32 noundef 516)
  call void @_Z22__spirv_ControlBarrieriii(i32 noundef 1, i32 noundef 1, i32 noundef 520)
  ret void
}

declare void @_Z22__spirv_ControlBarrieriii(i32 noundef, i32 noundef, i32 noundef)
