////////////////////////////////////////////////////////////////////////////////////////

// With -fsystem-debug option, ensure that declarations obtained by a using declaration have
// debug info generated.  sin() is declared through cmath with: using ::sin;
//
// Also ensure that no debug info for sin() is generated by default or if -fno-system-debug is used.

// Debug info for math library functions is not generated on Windows
// UNSUPPORTED: system-windows

// RUN: %clang -fsystem-debug    -emit-llvm -S -g %s     -o %t.system_debug.ll
// RUN: %clang                   -emit-llvm -S -g %s     -o %t.default.ll
// RUN: %clang -fno-system-debug -emit-llvm -S -g %s     -o %t.no_system_debug.ll

// Debug information for "sin" should be generated with -fsystem-debug
// RUN: FileCheck --check-prefix=CHECK-SYSTEM-DEBUG %s < %t.system_debug.ll

// No debug information for "sin" should be generated by default
// RUN: FileCheck --check-prefix=CHECK-DEFAULT         %s < %t.default.ll

// No debug information for "sin" should be generated with -fno-system-debug
// RUN: FileCheck --check-prefix=CHECK-NO-SYSTEM-DEBUG %s < %t.no_system_debug.ll

// CHECK-SYSTEM-DEBUG:        DISubprogram(name: "sin",
// CHECK-DEFAULT-NOT:         DISubprogram(name: "sin",
// CHECK-NO-SYSTEM-DEBUG-NOT: DISubprogram(name: "sin",

////////////////////////////////////////////////////////////////////////////////////////


#include <math.h>

int main() {
  float f;

  f=sin(1.32);
  return 0;
}
