= sycl_ext_oneapi_raw_kernel_arg

:source-highlighter: coderay
:coderay-linenums-mode: table

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en
:dpcpp: pass:[DPC++]
:endnote: &#8212;{nbsp}end{nbsp}note

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}


== Notice

[%hardbreaks]
Copyright (C) 2023 Intel Corporation.  All rights reserved.

Khronos(R) is a registered trademark and SYCL(TM) and SPIR(TM) are trademarks
of The Khronos Group Inc.  OpenCL(TM) is a trademark of Apple Inc. used by
permission by Khronos.


== Contact

To report problems with this extension, please open a new issue at:

https://github.com/intel/llvm/issues


== Dependencies

This extension is written against the SYCL 2020 revision 8 specification.  All
references below to the "core SYCL specification" or to section numbers in the
SYCL specification refer to that revision.


== Status

This is an experimental extension specification, intended to provide early
access to features and gather community feedback.  Interfaces defined in this
specification are implemented in {dpcpp}, but they are not finalized and may
change incompatibly in future versions of {dpcpp} without prior notice.
*Shipping software products should not rely on APIs defined in this
specification.*


== Backend support status

This extension is currently implemented in {dpcpp} for the Level Zero, OpenCL,
CUDA and Native CPU backends.  Attempting to use this extension on other
backends may result in undefined behavior.  Be aware that the compiler is not
able to issue a diagnostic to warn you if this happens.

A kernel argument that is a pointer must be constructed with the `pointer_arg`
overload described below.  Passing the byte representation of a pointer to the
byte overload is only guaranteed to bind that pointer on the Level Zero backend,
because a backend may take a pointer argument through a different entry point
than the one that takes plain bytes, and it cannot tell the two apart from the
bytes alone.


== Overview

When launching kernels that are represented as `sycl::kernel` objects,
developers must pass arguments via the `set_arg` or `set_args` functions.

There are situations where developers would like to pass a raw byte
representation of the kernel argument to the backend (e.g., when a single
`parallel_for` in the source code is used to invoke multiple kernels with
different arguments types, or when passing an argument to a built-in kernel
for which there is no equivalent type defined on the host).

=== Usage example

[source,c++]
----
int a;
char* opaque_type;
int nbytes;
...
h.set_arg(0, a);
h.set_arg(1, sycl::ext::oneapi::experimental::raw_kernel_arg(opaque_type, nbytes));
h.parallel_for(range, kernel);
----

An argument that is a pointer says so, since a backend may bind a pointer
through a different entry point than a sequence of bytes:

[source,c++]
----
namespace syclex = sycl::ext::oneapi::experimental;

int* ptr = sycl::malloc_device<int>(n, q);
...
h.set_arg(0, syclex::raw_kernel_arg(&ptr, syclex::pointer_arg));
h.parallel_for(range, kernel);
----


== Specification

=== Feature test macro

This extension provides a feature-test macro as described in the core SYCL
specification.  An implementation supporting this extension must predefine the
macro `SYCL_EXT_ONEAPI_RAW_KERNEL_ARG` to one of the values defined in the
table below.  Applications can test for the existence of this macro to
determine if the implementation supports this feature, or applications can test
the macro's value to determine which of the extension's features the
implementation supports.

[%header,cols="1,5"]
|===
|Value
|Description

|1
|Initial version of this extension.

|2
|Adds the `raw_kernel_arg` constructor that takes a pointer argument.
|===

=== The `raw_kernel_arg` class

This extension adds a new `raw_kernel_arg` class that can be used to declare
kernel arguments via a raw byte representation.

[source,c++]
----
namespace sycl::ext::oneapi::experimental {

  struct pointer_arg_t {};
  inline constexpr pointer_arg_t pointer_arg{};

  class raw_kernel_arg {
  public:
    raw_kernel_arg(const void* bytes, size_t count);

    template <typename T>
    raw_kernel_arg(T* const* pointer_location, pointer_arg_t tag);
  };

} // namespace sycl::ext::oneapi::experimental
----

[source,c++]
----
raw_kernel_arg(const void* bytes, size_t count);
----
_Preconditions_: `bytes` must point to an array of at least `count` bytes,
which is the byte representation of a kernel argument that is trivially
copyable.  If the argument is a pointer, only the Level Zero backend is
guaranteed to bind it; see _Backend support status_ above.

_Effects_: Constructs a `raw_kernel_arg` representing a view of the `count`
bytes starting at the address specified by `bytes`. Since the `raw_kernel_arg`
object is only a view, the caller must ensure that the lifetime of the `bytes`
memory lasts at least as long as the lifetime of the `raw_kernel_arg` object.

[source,c++]
----
template <typename T>
raw_kernel_arg(T* const* pointer_location, pointer_arg_t tag);
----
_Preconditions_: `pointer_location` must point to a pointer that is a valid
kernel argument, such as a pointer to memory allocated by one of the USM
allocation functions.

_Effects_: Constructs a `raw_kernel_arg` representing a view of the pointer
stored at `pointer_location`, to be bound as a pointer argument rather than as
the `sizeof(T*)` bytes it is made of. Since the `raw_kernel_arg` object is only
a view, the caller must ensure that the lifetime of the pointer object at
`pointer_location` lasts at least as long as the lifetime of the
`raw_kernel_arg` object.

[_Note:_ The constructor takes the address of the pointer, in keeping with the
byte overload taking the address of the bytes, so that passing the pointer
itself does not compile. _{endnote}_]

=== Using a raw kernel argument

Instances of `raw_kernel_arg` are passed to kernels via the existing `set_arg`
and `set_args` functions defined by the SYCL specification.

This extension adds a new overload of `set_arg`, as defined below.

[_Note:_ Since the definition of `set_args` says that it acts "as if each
argument in `args` was passed to `set_arg` ", adding a new overload of
`set_arg` is sufficient to change the behavior of `set_args`. _{endnote}_]

[source,c++]
----
void set_arg(int argIndex, sycl::ext::oneapi::experimental::raw_kernel_arg&& arg);
----
_Effects_: Sets the kernel argument associated with index `argIndex` using the
bytes represented by `arg`, or as a pointer argument if `arg` was constructed
with the `pointer_arg` overload.


== Issues

None.
