= sycl_ext_intel_cache_config
:source-highlighter: coderay
:coderay-linenums-mode: table

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en
:dpcpp: pass:[DPC++]

:blank: pass:[ +]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}

== Notice

[%hardbreaks]
Copyright (c) 2023 Intel Corporation.  All rights reserved.

Khronos(R) is a registered trademark and SYCL(TM) and SPIR(TM) are trademarks
of The Khronos Group Inc.  OpenCL(TM) is a trademark of Apple Inc. used by
permission by Khronos.

== Contact

To report problems with this extension, please open a new issue at:
https://github.com/intel/llvm/issues

== Contributors

Greg Lueck, Intel +
John Pennycook, Intel +
Artur Gainullin, Intel

== Dependencies

This extension is written against the SYCL 2020 specification, Revision 6 and
the following extensions:

- link:../experimental/sycl_ext_oneapi_properties.asciidoc[sycl_ext_oneapi_properties]
- link:../experimental/sycl_ext_oneapi_enqueue_functions.asciidoc[sycl_ext_oneapi_enqueue_functions]

== Status

This is an experimental extension specification, intended to provide early
access to features and gather community feedback.  Interfaces defined in this
specification are implemented in {dpcpp}, but they are not finalized and may
change incompatibly in future versions of {dpcpp} without prior notice.
*Shipping software products should not rely on APIs defined in this
specification.*

== Overview

There are devices where the same hardware resources are used for shared local
memory (SLM) and L1 data cache. Developers may want more L1 data cache or SLM
based on their application. This extension adds a kernel launch property
`cache_config` which provides a way to set the preferred cache configuration
for a kernel invocation.

=== Feature Test Macro

This extension provides a feature-test macro as described in the core SYCL
specification section 6.3.3 "Feature test macros".  Therefore, an
implementation supporting this extension must predefine the macro
`SYCL_EXT_INTEL_CACHE_CONFIG` to one of the values defined
in the table below.  Applications can test for the existence of this macro to
determine if the implementation supports this feature, or applications can test
the macro's value to determine which of the extension's APIs the implementation
supports.

[%header,cols="1,5"]
|===
|Value |Description
|1     |Initial extension version.  Base features are supported.
|===

=== Introduction

This extension introduces a new kernel launch property that specifies the
preferred cache configuration for a single kernel invocation. The recommended
way to apply the property is to pass it through a `launch_config` object to
one of the enqueue free functions defined in
link:../experimental/sycl_ext_oneapi_enqueue_functions.asciidoc[
sycl_ext_oneapi_enqueue_functions] (such as `parallel_for` or `nd_launch`).
The property is applicable both to kernels expressed as SYCL lambdas/function
objects and to free function kernels defined by
link:../experimental/sycl_ext_oneapi_free_function_kernels.asciidoc[
sycl_ext_oneapi_free_function_kernels].

Because `cache_config` is a launch-time property rather than a compile-time
kernel property, it is not embedded into the kernel's type and the cache
configuration can be chosen independently for each invocation of the same
kernel.

=== Cache Config Property

```c++
namespace sycl::ext::intel::experimental {

enum class cache_config_enum : /*unspecified*/ { large_slm, large_data };

inline constexpr cache_config_enum large_slm =
    cache_config_enum::large_slm;
inline constexpr cache_config_enum large_data =
    cache_config_enum::large_data;

struct cache_config {
  cache_config(cache_config_enum v) : value(v) {}
  cache_config_enum value;
};

} // namespace sycl::ext::intel::experimental
```

The `cache_config` property provides a way to set the preferred cache
configuration for a kernel invocation. The following values are supported:

 * `large_slm`: Prefer having larger shared local memory and smaller L1 data
                cache. In this case the driver will ensure that all workgroups
                will have enough SLM to run.

 * `large_data`: Prefer having larger L1 data cache and smaller shared local
                 memory. In this case SLM size may be shrunk (which may result
                 in workgroups spawning as there will be not enough SLM to
                 handle multiple workgroups) but L1 data cache will be bigger.
                 There may be rare use cases when this is beneficial.

The `cache_config` property must be passed to a kernel invocation through a
`launch_config` object.  At most one `cache_config` value may be passed to
any single kernel invocation.

Backends that do not support this extension may accept and ignore this
property.

=== Usage Examples

Simple examples of using this extension are shown below.

==== parallel_for and nd_launch

```c++
#include <sycl/sycl.hpp>

namespace syclex = sycl::ext::oneapi::experimental;
namespace intelex = sycl::ext::intel::experimental;

int main() {
    sycl::queue q;
    syclex::properties props{intelex::cache_config{intelex::large_slm}};

    // Range-based launch.
    syclex::parallel_for(q,
        syclex::launch_config{sycl::range<1>{1024}, props},
        [=](sycl::item<1> i) { /* kernel code */ });

    // nd_range-based launch.
    syclex::nd_launch(q,
        syclex::launch_config{sycl::nd_range<1>{{1024}, {64}}, props},
        [=](sycl::nd_item<1> i) { /* kernel code */ });

    q.wait();
}
```

==== Free function kernels

For a kernel declared with the free function kernel syntax, the property is
passed to `nd_launch` via the same `launch_config` mechanism:

```c++
#include <sycl/sycl.hpp>

namespace syclex = sycl::ext::oneapi::experimental;
namespace intelex = sycl::ext::intel::experimental;

SYCL_EXT_ONEAPI_FUNCTION_PROPERTY((syclex::nd_range_kernel<1>))
void my_kernel(float *ptr) { /* kernel code */ }

int main() {
  sycl::queue q;
  float *ptr = sycl::malloc_shared<float>(1024, q);

  syclex::launch_config cfg{
    sycl::nd_range<1>{{1024}, {64}},
    syclex::properties{intelex::cache_config{intelex::large_slm}}
  };
  syclex::nd_launch(q, cfg, syclex::kernel_function<my_kernel>, ptr);

  q.wait();
}
```

==== Different cache configurations for different launches of the same kernel

Because `cache_config` is a runtime property, different invocations of the
same kernel can use different cache configurations.

```c++
#include <sycl/sycl.hpp>

namespace syclex = sycl::ext::oneapi::experimental;
namespace intelex = sycl::ext::intel::experimental;

SYCL_EXT_ONEAPI_FUNCTION_PROPERTY((syclex::nd_range_kernel<1>))
void my_kernel(float *ptr) { /* kernel code */ }

int main() {
  sycl::queue q;
  sycl::context ctxt = q.get_context();
  float *ptr = sycl::malloc_shared<float>(1024, q);

  auto bundle =
      syclex::get_kernel_bundle<my_kernel, sycl::bundle_state::executable>(ctxt);
  sycl::kernel k = bundle.ext_oneapi_get_kernel<my_kernel>();

  sycl::nd_range<1> ndr{{1024}, {64}};

  // First launch with large SLM.
  syclex::nd_launch(q,
      syclex::launch_config{ndr,
          syclex::properties{intelex::cache_config{intelex::large_slm}}},
      k, ptr);

  // Second launch of the same kernel with large data cache.
  syclex::nd_launch(q,
      syclex::launch_config{ndr,
          syclex::properties{intelex::cache_config{intelex::large_data}}},
      k, ptr);

  q.wait();
}
```

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2022-03-01|Artur Gainullin|*Initial public working draft*
|2|2026-04-24|Artur Gainullin|*Clarify `cache_config` as a kernel launch property; remove embedding via `get(properties_tag)`*
|========================================
