//===-- SYCLTargetParser.cpp - SYCL target device resolution --------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
// This file implement a TargetParser for SYCL Offloading kind.
//===----------------------------------------------------------------------===//

#include "llvm/TargetParser/SYCLTargetParser.h"
#include "llvm/ADT/StringSwitch.h"

using namespace llvm;

StringRef sycl_target::resolveGenDevice(StringRef DeviceName) {
  return StringSwitch<StringRef>(DeviceName)
      .Cases({"intel_gpu_bdw", "intel_gpu_8_0_0"}, "bdw")
      .Cases({"intel_gpu_skl", "intel_gpu_9_0_9"}, "skl")
      .Cases({"intel_gpu_kbl", "intel_gpu_9_1_9"}, "kbl")
      .Cases({"intel_gpu_cfl", "intel_gpu_9_2_9"}, "cfl")
      .Cases({"intel_gpu_apl", "intel_gpu_bxt", "intel_gpu_9_3_0"}, "apl")
      .Cases({"intel_gpu_glk", "intel_gpu_9_4_0"}, "glk")
      .Cases({"intel_gpu_whl", "intel_gpu_9_5_0"}, "whl")
      .Cases({"intel_gpu_aml", "intel_gpu_9_6_0"}, "aml")
      .Cases({"intel_gpu_cml", "intel_gpu_9_7_0"}, "cml")
      .Cases({"intel_gpu_icllp", "intel_gpu_icl", "intel_gpu_11_0_0"}, "icllp")
      .Cases({"intel_gpu_ehl", "intel_gpu_jsl", "intel_gpu_11_2_0"}, "ehl")
      .Cases({"intel_gpu_tgllp", "intel_gpu_tgl", "intel_gpu_12_0_0"}, "tgllp")
      .Cases({"intel_gpu_rkl", "intel_gpu_12_1_0"}, "rkl")
      .Cases({"intel_gpu_adl_s", "intel_gpu_rpl_s", "intel_gpu_12_2_0"},
             "adl_s")
      .Cases({"intel_gpu_adl_p", "intel_gpu_12_3_0"}, "adl_p")
      .Cases({"intel_gpu_adl_n", "intel_gpu_12_4_0"}, "adl_n")
      .Cases({"intel_gpu_dg1", "intel_gpu_12_10_0"}, "dg1")
      .Cases({"intel_gpu_acm_g10", "intel_gpu_dg2_g10", "intel_gpu_12_55_8"},
             "acm_g10")
      .Cases({"intel_gpu_acm_g11", "intel_gpu_dg2_g11", "intel_gpu_12_56_5"},
             "acm_g11")
      .Cases({"intel_gpu_acm_g12", "intel_gpu_dg2_g12", "intel_gpu_12_57_0"},
             "acm_g12")
      .Cases({"intel_gpu_pvc", "intel_gpu_12_60_7"}, "pvc")
      .Cases({"intel_gpu_pvc_vg", "intel_gpu_12_61_7"}, "pvc_vg")
      .Cases({"intel_gpu_mtl_u", "intel_gpu_mtl_s", "intel_gpu_arl_u",
              "intel_gpu_arl_s", "intel_gpu_12_70_4"},
             "mtl_u")
      .Cases({"intel_gpu_mtl_h", "intel_gpu_12_71_4"}, "mtl_h")
      .Cases({"intel_gpu_arl_h", "intel_gpu_12_74_4"}, "arl_h")
      .Cases({"intel_gpu_bmg_g21", "intel_gpu_20_1_4"}, "bmg_g21")
      .Cases({"intel_gpu_bmg_g31", "intel_gpu_20_2_0"}, "bmg_g31")
      .Cases({"intel_gpu_lnl_m", "intel_gpu_20_4_4"}, "lnl_m")
      .Cases({"intel_gpu_ptl_h", "intel_gpu_30_0_4"}, "ptl_h")
      .Cases({"intel_gpu_ptl_u", "intel_gpu_30_1_1"}, "ptl_u")
      .Cases({"intel_gpu_wcl", "intel_gpu_30_3_0"}, "wcl")
      .Cases({"intel_gpu_nvl_s", "intel_gpu_nvl_hx", "intel_gpu_nvl_ul",
              "intel_gpu_30_4_0"},
             "nvl_s")
      .Cases({"intel_gpu_nvl_u", "intel_gpu_nvl_h", "intel_gpu_30_5_0"},
             "nvl_u")
      .Cases({"intel_gpu_nvl_p", "intel_gpu_35_10_0"}, "nvl_p")
      .Cases({"intel_gpu_cri", "intel_gpu_35_11_0"}, "cri")
      .Case("intel_gpu_dg2", "dg2")
      .Case("intel_gpu_mtl", "mtl")
      .Case("intel_gpu_bmg", "bmg")
      .Case("intel_gpu_ptl", "ptl")
      .Case("nvidia_gpu_sm_50", "sm_50")
      .Case("nvidia_gpu_sm_52", "sm_52")
      .Case("nvidia_gpu_sm_53", "sm_53")
      .Case("nvidia_gpu_sm_60", "sm_60")
      .Case("nvidia_gpu_sm_61", "sm_61")
      .Case("nvidia_gpu_sm_62", "sm_62")
      .Case("nvidia_gpu_sm_70", "sm_70")
      .Case("nvidia_gpu_sm_72", "sm_72")
      .Case("nvidia_gpu_sm_75", "sm_75")
      .Case("nvidia_gpu_sm_80", "sm_80")
      .Case("nvidia_gpu_sm_86", "sm_86")
      .Case("nvidia_gpu_sm_87", "sm_87")
      .Case("nvidia_gpu_sm_89", "sm_89")
      .Case("nvidia_gpu_sm_90", "sm_90")
      .Case("nvidia_gpu_sm_90a", "sm_90a")
      .Case("amd_gpu_gfx700", "gfx700")
      .Case("amd_gpu_gfx701", "gfx701")
      .Case("amd_gpu_gfx702", "gfx702")
      .Case("amd_gpu_gfx703", "gfx703")
      .Case("amd_gpu_gfx704", "gfx704")
      .Case("amd_gpu_gfx705", "gfx705")
      .Case("amd_gpu_gfx801", "gfx801")
      .Case("amd_gpu_gfx802", "gfx802")
      .Case("amd_gpu_gfx803", "gfx803")
      .Case("amd_gpu_gfx805", "gfx805")
      .Case("amd_gpu_gfx810", "gfx810")
      .Case("amd_gpu_gfx900", "gfx900")
      .Case("amd_gpu_gfx902", "gfx902")
      .Case("amd_gpu_gfx904", "gfx904")
      .Case("amd_gpu_gfx906", "gfx906")
      .Case("amd_gpu_gfx908", "gfx908")
      .Case("amd_gpu_gfx909", "gfx909")
      .Case("amd_gpu_gfx90a", "gfx90a")
      .Case("amd_gpu_gfx90c", "gfx90c")
      .Case("amd_gpu_gfx940", "gfx940")
      .Case("amd_gpu_gfx941", "gfx941")
      .Case("amd_gpu_gfx942", "gfx942")
      .Case("amd_gpu_gfx1010", "gfx1010")
      .Case("amd_gpu_gfx1011", "gfx1011")
      .Case("amd_gpu_gfx1012", "gfx1012")
      .Case("amd_gpu_gfx1013", "gfx1013")
      .Case("amd_gpu_gfx1030", "gfx1030")
      .Case("amd_gpu_gfx1031", "gfx1031")
      .Case("amd_gpu_gfx1032", "gfx1032")
      .Case("amd_gpu_gfx1033", "gfx1033")
      .Case("amd_gpu_gfx1034", "gfx1034")
      .Case("amd_gpu_gfx1035", "gfx1035")
      .Case("amd_gpu_gfx1036", "gfx1036")
      .Case("amd_gpu_gfx1100", "gfx1100")
      .Case("amd_gpu_gfx1101", "gfx1101")
      .Case("amd_gpu_gfx1102", "gfx1102")
      .Case("amd_gpu_gfx1103", "gfx1103")
      .Case("amd_gpu_gfx1150", "gfx1150")
      .Case("amd_gpu_gfx1151", "gfx1151")
      .Case("amd_gpu_gfx1200", "gfx1200")
      .Case("amd_gpu_gfx1201", "gfx1201")
      .Default("");
}

SmallString<64> sycl_target::getGenDeviceMacro(StringRef DeviceName) {
  StringRef Ext =
      StringSwitch<StringRef>(DeviceName)
          .Case("bdw", "INTEL_GPU_BDW")
          .Case("skl", "INTEL_GPU_SKL")
          .Case("kbl", "INTEL_GPU_KBL")
          .Case("cfl", "INTEL_GPU_CFL")
          .Cases({"apl", "bxt"}, "INTEL_GPU_APL")
          .Case("glk", "INTEL_GPU_GLK")
          .Case("whl", "INTEL_GPU_WHL")
          .Case("aml", "INTEL_GPU_AML")
          .Case("cml", "INTEL_GPU_CML")
          .Cases({"icllp", "icl"}, "INTEL_GPU_ICLLP")
          .Cases({"ehl", "jsl"}, "INTEL_GPU_EHL")
          .Cases({"tgllp", "tgl"}, "INTEL_GPU_TGLLP")
          .Case("rkl", "INTEL_GPU_RKL")
          .Cases({"adl_s", "rpl_s"}, "INTEL_GPU_ADL_S")
          .Case("adl_p", "INTEL_GPU_ADL_P")
          .Case("adl_n", "INTEL_GPU_ADL_N")
          .Case("dg1", "INTEL_GPU_DG1")
          .Case("dg2", "INTEL_GPU_DG2")
          .Cases({"acm_g10", "dg2_g10"}, "INTEL_GPU_ACM_G10")
          .Cases({"acm_g11", "dg2_g11"}, "INTEL_GPU_ACM_G11")
          .Cases({"acm_g12", "dg2_g12"}, "INTEL_GPU_ACM_G12")
          .Case("pvc", "INTEL_GPU_PVC")
          .Case("pvc_vg", "INTEL_GPU_PVC_VG")
          .Case("mtl", "INTEL_GPU_MTL")
          .Cases({"mtl_u", "mtl_s", "arl_u", "arl_s"}, "INTEL_GPU_MTL_U")
          .Case("mtl_h", "INTEL_GPU_MTL_H")
          .Case("arl_h", "INTEL_GPU_ARL_H")
          .Case("bmg", "INTEL_GPU_BMG")
          .Case("bmg_g21", "INTEL_GPU_BMG_G21")
          .Case("bmg_g31", "INTEL_GPU_BMG_G31")
          .Case("lnl_m", "INTEL_GPU_LNL_M")
          .Case("ptl", "INTEL_GPU_PTL")
          .Case("ptl_h", "INTEL_GPU_PTL_H")
          .Case("ptl_u", "INTEL_GPU_PTL_U")
          .Case("wcl", "INTEL_GPU_WCL")
          .Case("nvl_s", "INTEL_GPU_NVL_S")
          .Case("nvl_u", "INTEL_GPU_NVL_U")
          .Case("nvl_p", "INTEL_GPU_NVL_P")
          .Case("cri", "INTEL_GPU_CRI")
          .Case("sm_50", "NVIDIA_GPU_SM_50")
          .Case("sm_52", "NVIDIA_GPU_SM_52")
          .Case("sm_53", "NVIDIA_GPU_SM_53")
          .Case("sm_60", "NVIDIA_GPU_SM_60")
          .Case("sm_61", "NVIDIA_GPU_SM_61")
          .Case("sm_62", "NVIDIA_GPU_SM_62")
          .Case("sm_70", "NVIDIA_GPU_SM_70")
          .Case("sm_72", "NVIDIA_GPU_SM_72")
          .Case("sm_75", "NVIDIA_GPU_SM_75")
          .Case("sm_80", "NVIDIA_GPU_SM_80")
          .Case("sm_86", "NVIDIA_GPU_SM_86")
          .Case("sm_87", "NVIDIA_GPU_SM_87")
          .Case("sm_89", "NVIDIA_GPU_SM_89")
          .Case("sm_90", "NVIDIA_GPU_SM_90")
          .Case("sm_90a", "NVIDIA_GPU_SM_90A")
          .Case("gfx700", "AMD_GPU_GFX700")
          .Case("gfx701", "AMD_GPU_GFX701")
          .Case("gfx702", "AMD_GPU_GFX702")
          .Case("gfx703", "AMD_GPU_GFX703")
          .Case("gfx704", "AMD_GPU_GFX704")
          .Case("gfx705", "AMD_GPU_GFX705")
          .Case("gfx801", "AMD_GPU_GFX801")
          .Case("gfx802", "AMD_GPU_GFX802")
          .Case("gfx803", "AMD_GPU_GFX803")
          .Case("gfx805", "AMD_GPU_GFX805")
          .Case("gfx810", "AMD_GPU_GFX810")
          .Case("gfx900", "AMD_GPU_GFX900")
          .Case("gfx902", "AMD_GPU_GFX902")
          .Case("gfx904", "AMD_GPU_GFX904")
          .Case("gfx906", "AMD_GPU_GFX906")
          .Case("gfx908", "AMD_GPU_GFX908")
          .Case("gfx909", "AMD_GPU_GFX909")
          .Case("gfx90a", "AMD_GPU_GFX90A")
          .Case("gfx90c", "AMD_GPU_GFX90C")
          .Case("gfx940", "AMD_GPU_GFX940")
          .Case("gfx941", "AMD_GPU_GFX941")
          .Case("gfx942", "AMD_GPU_GFX942")
          .Case("gfx1010", "AMD_GPU_GFX1010")
          .Case("gfx1011", "AMD_GPU_GFX1011")
          .Case("gfx1012", "AMD_GPU_GFX1012")
          .Case("gfx1013", "AMD_GPU_GFX1013")
          .Case("gfx1030", "AMD_GPU_GFX1030")
          .Case("gfx1031", "AMD_GPU_GFX1031")
          .Case("gfx1032", "AMD_GPU_GFX1032")
          .Case("gfx1033", "AMD_GPU_GFX1033")
          .Case("gfx1034", "AMD_GPU_GFX1034")
          .Case("gfx1035", "AMD_GPU_GFX1035")
          .Case("gfx1036", "AMD_GPU_GFX1036")
          .Case("gfx1100", "AMD_GPU_GFX1100")
          .Case("gfx1101", "AMD_GPU_GFX1101")
          .Case("gfx1102", "AMD_GPU_GFX1102")
          .Case("gfx1103", "AMD_GPU_GFX1103")
          .Case("gfx1150", "AMD_GPU_GFX1150")
          .Case("gfx1151", "AMD_GPU_GFX1151")
          .Case("gfx1200", "AMD_GPU_GFX1200")
          .Case("gfx1201", "AMD_GPU_GFX1201")
          .Default("");
  SmallString<64> Macro;
  if (!Ext.empty()) {
    Macro = "__SYCL_TARGET_";
    Macro += Ext;
    Macro += "__";
  }
  return Macro;
}

StringRef sycl_target::getGenGRFFlag(StringRef GRFMode) {
  return StringSwitch<StringRef>(GRFMode)
      .Case("auto", "-ze-intel-enable-auto-large-GRF-mode")
      .Case("small", "-ze-intel-128-GRF-per-thread")
      .Case("large", "-ze-opt-large-register-file")
      .Default("");
}
