SPV_INTEL_vector_compute
========================

Name Strings
------------

SPV_INTEL_vector_compute

Contact
-------

To report problems or to provide input on this extension, please open a new issue at:
https://github.com/intel/llvm/issues

Contributors
------------

- Gang Chen, Intel
- Aleksandr Bezzubikov, Intel
- Aleksander Us, Intel
- Nikita Rudenko, Intel
- Konstantin Vladimirov, Intel
- Alexey Sachkov, Intel
- Mariusz Merecki, Intel


Notice
------

Copyright (c) 2020 Intel Corporation. All rights reserved.

Status
------

Working Draft

This is a preview extension specification, intended to provide early access to a feature for review and community feedback. When the feature matures, this specification may be released as a formal extension.

Because the interfaces defined by this specification are not final and are subject to change they are not intended to be used by shipping software products. If you are interested in using this feature in your software product, please let us know!


Version
-------

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2020-05-06
| Revision           | 3
|========================================

Dependencies
------------

This extension is written against the SPIR-V Specification,
Version 1.5, Revision 2, Unified

This extension requires SPIR-V 1.0.

Overview
--------

This extension adds new capability, execution mode and decorations
to support INTEL vector compute specific features in SPIR-V.


Extension Name
--------------

To use this extension within a SPIR-V module, the following
*OpExtension* must be present in the module:

----
OpExtension "SPV_INTEL_vector_compute"
----

Modifications to the SPIR-V Specification, Version 1.5, Revision 2, Unified
---------------------------------------------------------------------------

Modify Section 3.6, Execution Mode, add the following rows to the Execution Mode table:

--
[cols="1,20,10,10",options="header",width = "80%"]
|====
  2+^| Execution Mode  | Enabling Capabilities | Extra Operands
| 5618 | *SharedLocalMemorySizeINTEL* +
Specifies the size of shared memory required by kernel, in bytes.

'Size' is an unsigned 32-bit integer.

See the client API specification for more detail.
| *VectorComputeINTEL* | <<Literal, 'Literal'>> _Size_
|====
--

Modify Section 3.20, Decoration, add the following rows to the Decoration table:

--
[cols="1,20,10,10",options="header",width = "80%"]
|====
  2+^| Decoration  | Enabling Capabilities | Extra Operands
| 5626 | *VectorComputeFunctionINTEL* +
Apply to a function definition to specify that this function is a vector compute function.

See the client API specification for more detail.
| *VectorComputeINTEL* |
| 5627 | *StackCallINTEL* +
Apply to a function definition to specify that this function is a stack call function.

See the client API specification for more detail.
| *VectorComputeINTEL* |
|====
--

Modify Section 3.31, Capability, add the following row the 'Capability' table:
--
[cols="1,20,10,10",options="header",width = "80%"]
|====
  2+^| Capability      |     Implicitly Declares    | Enabled by Extension
| 5617 | *VectorComputeINTEL* +
Enables the use of *SharedLocalMemorySizeINTEL* execution mode and *VectorComputeFunctionINTEL* and *StackCallINTEL* decorations.

See the client API specification for more detail.
|| *SPV_INTEL_vector_compute*
|====
--

Issues
------


Revision History
----------------

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2020-04-17|Mariusz Merecki|Initial revision
|2|2020-04-24|Mariusz Merecki|Assigned token number to *VectorComputeKernelINTEL*
|3|2020-05-06|Mariusz Merecki|Removed *VectorComputeKernelINTEL*, *KernelArgumentTypeINTEL* and *KernelArgumentDescINTEL*. Added *VectorComputeFunctionINTEL*.
|========================================
