SPV_INTEL_optimization_hints
============================

Name Strings
------------

SPV_INTEL_optimization_hints

Contact
-------

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Headers

Contributors
------------

- Dmitry Sidorov, Intel
- Alexey Sachkov, Intel
- Alexey Sotkin, Intel
- Ben Ashbaugh, Intel

Notice
------

Copyright (c) 2020 Intel Corporation.  All rights reserved.

Status
------

Working Draft

This is a preview extension specification, intended to provide early access to a
feature for review and community feedback. When the feature matures, this
specification may be released as a formal extension.

Because the interfaces defined by this specification are not final and are
subject to change they are not intended to be used by shipping software
products.

Version
-------

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2020-06-07
| Revision           | H
|========================================

Dependencies
------------

This extension is written against the SPIR-V Specification,
Version 1.5 Revision 2.

This extension requires SPIR-V 1.0.

Overview
--------

This extension adds *OpAssumeTrueINTEL* and *OpExpectINTEL* instructions that
are mapped to ‘llvm.assume’ and ‘llvm.expect’ intrinsics respectively. That is
required to save optimization hints through LLVM IR to SPIR-V transformation.

Extension Name
--------------

To use this extension within a SPIR-V module, the following *OpExtension* must
be present in the module:

----
OpExtension "SPV_INTEL_optimization_hints"
----

New Capabilities
----------------
This extension introduces a new capability:

----
OptimizationHintsINTEL
----

New Instructions
----------------
Instructions added under the *OptimizationHintsINTEL* capability:

----
OpExpectINTEL
OpAssumeTrueINTEL
----

Token Number Assignments
------------------------
[width="45%",cols="30,15"]
|===============================
| OptimizationHintsINTEL | 5629
| OpAssumeTrueINTEL      | 5630
| OpExpectINTEL          | 5631
|===============================

Modifications to the SPIR-V Specification, Version 1.5
------------------------------------------------------

Capabilities
~~~~~~~~~~~~

Modify Section 3.31, "Capability", adding these rows to the Capability table:

--
[options="header"]
|====
2+^| Capability ^| Depends On
| 5629 | *OptimizationHintsINTEL* +
Allow to use OpAssumeTrueINTEL and OpExpectINTEL instructions |
|====
--

Instructions
~~~~~~~~~~~~

In section 3.32.1, Miscellaneous Instructions, add a new instruction:

[cols="3", width="100%"]
|=====
2+^|*OpAssumeTrueINTEL* +
The instruction allows the optimizer to assume that the provided _Condition_ is
always true whenever the control flow reaches the instruction. If the
_Condition_ is violated during execution, the behavior is undefined.

The type of _Condition_ must be a scalar _Boolean_.
| Capability:
*OptimizationHintsINTEL*

| 2 | 5630 | Condition <id>
|=====

[cols="6", width="100%"]
|=====
5+^|*OpExpectINTEL* +

Provides information for optimizers that the most probable value of _Value_ is
_ExpectedValue_ and makes a copy of _Value_.

This instruction can be safely replaced with an entityi referenced by _Value_.

The type of _Value_ and _ExpectedValue_ must be the same as _Result Type_,
which must be of _Integer_ or _Boolean_ type.

| Capability:
*OptimizationHintsINTEL*

| 5 | 5631 | <id> +
Result Type | Result <id> | Value <id> | ExpectedValue <id>
|=====

Issues
------

1) From https://llvm.org/docs/LangRef.html#llvm-expect-intrinsic
_This is an overloaded intrinsic. You can use llvm.expect on any integer bit
width._
Shall we put a dependency on SPV_INTEL_arbitrary_precision_integers extension?

Resolution:

No need.

Revision History
----------------

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|A|2020-04-02|Dmitry Sidorov|Initial revision
|B|2020-04-03|Dmitry Sidorov|Switch Expected from Decoration to instruction
|C|2020-04-07|Dmitry Sidorov|Apply Alexey's suggestions
|D|2020-04-08|Dmitry Sidorov|Rename the extension to SPV_INTEL_optimization_hints
|E|2020-04-08|Dmitry Sidorov|Assign reserved values
|F|2020-04-30|Dmitry Sidorov|Switch AssumeTrue from Decoration to instruction
|G|2020-05-12|Dmitry Sidorov|Fix typos
|H|2020-06-07|Dmitry Sidorov|Update instructions' descriptions
|========================================

