= sycl_ext_oneapi_address_space_cast

:source-highlighter: coderay
:coderay-linenums-mode: table

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en
:dpcpp: pass:[DPC++]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}


== Notice

[%hardbreaks]
Copyright (C) 2023-2023 Intel Corporation.  All rights reserved.

Khronos(R) is a registered trademark and SYCL(TM) and SPIR(TM) are trademarks
of The Khronos Group Inc.  OpenCL(TM) is a trademark of Apple Inc. used by
permission by Khronos.


== Contact

To report problems with this extension, please open a new issue at:

https://github.com/intel/llvm/issues


== Dependencies

This extension is written against the SYCL 2020 revision 7 specification.  All
references below to the "core SYCL specification" or to section numbers in the
SYCL specification refer to that revision.


== Status

This is a proposed extension specification, intended to gather community
feedback.  Interfaces defined in this specification may not be implemented yet
or may be in a preliminary state.  The specification itself may also change in
incompatible ways before it is finalized.  *Shipping software products should
not rely on APIs defined in this specification.*


== Overview

The `sycl::address_space_cast` function in SYCL 2020 does two things: 1) checks
whether a given raw pointer can be cast to a specific address space; and 2)
performs the casting operation. In cases where the developer is attempting to
assert that a raw pointer points to an object in a specific address space, the
checks from 1) are not required and may have undesirable performance impact.

This extension separates `sycl::address_space_cast` into two functions:

- `static_address_space_cast`, which casts with no checks.
- `dynamic_address_space_cast`, which casts with checks.


== Specification

=== Feature test macro

This extension provides a feature-test macro as described in the core SYCL
specification.  An implementation supporting this extension must predefine the
macro `SYCL_EXT_ONEAPI_ADDRESS_SPACE_CAST` to one of the values defined in the
table below.  Applications can test for the existence of this macro to
determine if the implementation supports this feature, or applications can test
the macro's value to determine which of the extension's features the
implementation supports.

[%header,cols="1,5"]
|===
|Value
|Description

|1
|The APIs of this experimental extension are not versioned, so the
 feature-test macro always has this value.
|===


=== Address space cast functions

[source,c++]
----
namespace sycl::ext::oneapi::experimental {

template <access::address_space Space, access::decorated DecorateAddress,
          typename ElementType>
multi_ptr<ElementType, Space, DecorateAddress>
static_address_space_cast(ElementType* ptr);

template <access::address_space Space, access::decorated DecorateAddress,
          typename ElementType>
multi_ptr<ElementType, Space, DecorateAddress>
dynamic_address_space_cast(ElementType* ptr);

} // namespace sycl::ext::oneapi::experimental
----

[source,c++]
----
template <access::address_space Space, access::decorated DecorateAddress,
          typename ElementType>
multi_ptr<ElementType, Space, DecorateAddress>
static_address_space_cast(ElementType* ptr);
----
_Preconditions_: `ptr` points to an object allocated in the address space
designated by `Space`.

_Returns_: A `multi_ptr` with the specified address space and decoration that
points to the same object as `ptr`.

[source,c++]
----
template <access::address_space Space, access::decorated DecorateAddress,
          typename ElementType>
multi_ptr<ElementType, Space, DecorateAddress>
dynamic_address_space_cast(ElementType* ptr);
----
_Returns_: A `multi_ptr` with the specified address space and decoration that
points to the same object as `ptr` if `ptr` points to an object allocated in
the address space designated by `Space`, and `nullptr` otherwise.

_Diagnostics_: Implementations using address space deduction must issue a
diagnostic if `ptr` does not point to an object allocated in the address space
designated by `Space`.


== Implementation notes

For SPIR-V backends, `static_address_space_cast` corresponds to
`OpGenericCastToPtr`, and `dynamic_address_space_cast` corresponds to
`OpGenericCastToPtrExplicit`.

Generally speaking, it is expected that a `static_address_space_cast` can
simply attach new decoration(s) to the raw pointer (or do nothing), while
a `dynamic_address_space_cast` will have to inspect the address of the
raw pointer to determine which region of memory it points to.


== Issues

. `static_address_space_cast` and `dynamic_address_space_cast` are long names.
+
--
*UNRESOLVED*:
Dropping one of the words would be less verbose; either `static_address_cast`
or `static_space_cast` could be considered.

. Some developers may expect a `dynamic_address_space_cast` to succeed if the
pointer continues to work, irrespective of where the object the pointer points
to was allocated. For example, some CPU implementations may treat global and
local pointers equivalently in many situations.
+
--
*UNRESOLVED*:
The current description of `dynamic_address_space_cast` requires
implementations to track precisely which address space a pointer is associated
with, in order to ensure that using the result of a dynamic cast is always
safe. If we can identify use-cases for the more relaxed behavior, it would
make sense to introduce either a third type of cast or some global check that
two address spaces use the same representation and are thus "compatible".
