// RUN: %clangxx -I %sycl_include -S -emit-llvm -fsycl-device-only %s -o - -Xclang -disable-llvm-passes | FileCheck %s

#include <CL/sycl.hpp>

using namespace sycl;

template <typename T, template <typename> class O, typename G>
void group_operations(G g) {
  T res;
  res = reduce_over_group(g, T{}, O<T>{});
  res = inclusive_scan_over_group(g, T{}, O<T>{});
  res = exclusive_scan_over_group(g, T{}, O<T>{});
}

template <typename T, typename G> void binary_operations(G g) {
  if constexpr (!detail::is_floating_point<T>::value) {
    group_operations<T, bit_and>(g);
    group_operations<T, bit_or>(g);
    group_operations<T, bit_xor>(g);
  }
  group_operations<T, maximum>(g);
  group_operations<T, minimum>(g);
  group_operations<T, multiplies>(g);
  group_operations<T, plus>(g);
}

template <typename T, typename G> void signed_unsigned(G g) {
  binary_operations<T>(g);
  binary_operations<detail::make_unsigned_t<T>>(g);
}

template <typename G> void test(G g) {
  signed_unsigned<int8_t>(g);
  signed_unsigned<int16_t>(g);
  signed_unsigned<int32_t>(g);
  signed_unsigned<int64_t>(g);
  signed_unsigned<half>(g);
  signed_unsigned<float>(g);
  signed_unsigned<double>(g);
}

SYCL_EXTERNAL void test_group(group<> g) { test(g); }

// int8_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 2, i32 %[[#]])

// uint8_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 2, i32 %[[#]])

// int16_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 2, i32 %[[#]])

// uint16_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 2, i32 %[[#]])

// int32_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 2, i32 2, i32 %[[#]])

// uint32_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 2, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 2, i32 2, i32 %[[#]])

// int64_t (Linux: long, Windows: long long)
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{l|x}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{l|x}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{l|x}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMaxjj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMaxjj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMaxjj{{l|x}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMinjj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMinjj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMinjj{{l|x}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{l|x}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{l|x}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{l|x}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{l|x}}(i32 2, i32 2, i64 %[[#]])

// uint64_t (Linux: unsigned long, Windows: unsigned long long)
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{m|y}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{m|y}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{m|y}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMaxjj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMaxjj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMaxjj{{m|y}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMinjj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMinjj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMinjj{{m|y}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{m|y}}(i32 2, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{m|y}}(i32 2, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{m|y}}(i32 2, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{m|y}}(i32 2, i32 2, i64 %[[#]])

// half
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMaxjjDF16_(i32 2, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMaxjjDF16_(i32 2, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMaxjjDF16_(i32 2, i32 2, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMinjjDF16_(i32 2, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMinjjDF16_(i32 2, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMinjjDF16_(i32 2, i32 2, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupNonUniformFMuljjDF16_(i32 2, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupNonUniformFMuljjDF16_(i32 2, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupNonUniformFMuljjDF16_(i32 2, i32 2, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFAddjjDF16_(i32 2, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFAddjjDF16_(i32 2, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFAddjjDF16_(i32 2, i32 2, half %[[#]])

// float
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMaxjjf(i32 2, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMaxjjf(i32 2, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMaxjjf(i32 2, i32 2, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMinjjf(i32 2, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMinjjf(i32 2, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMinjjf(i32 2, i32 2, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupNonUniformFMuljjf(i32 2, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupNonUniformFMuljjf(i32 2, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupNonUniformFMuljjf(i32 2, i32 2, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFAddjjf(i32 2, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFAddjjf(i32 2, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFAddjjf(i32 2, i32 2, float %[[#]])

// double
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMaxjjd(i32 2, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMaxjjd(i32 2, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMaxjjd(i32 2, i32 2, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMinjjd(i32 2, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMinjjd(i32 2, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMinjjd(i32 2, i32 2, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupNonUniformFMuljjd(i32 2, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupNonUniformFMuljjd(i32 2, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupNonUniformFMuljjd(i32 2, i32 2, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFAddjjd(i32 2, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFAddjjd(i32 2, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFAddjjd(i32 2, i32 2, double %[[#]])

SYCL_EXTERNAL void test_sub_group(sub_group g) { test(g); }

// int8_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 2, i32 %[[#]])

// uint8_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 2, i32 %[[#]])

// int16_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 2, i32 %[[#]])

// uint16_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 2, i32 %[[#]])

// int32_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMaxjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupSMinjji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljji(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjji(i32 3, i32 2, i32 %[[#]])

// uint32_t
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMaxjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupUMinjjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupNonUniformIMuljjj(i32 3, i32 2, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 0, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 1, i32 %[[#]])
// CHECK: %{{.*}} = call spir_func i32 @_Z[[#]]__spirv_GroupIAddjjj(i32 3, i32 2, i32 %[[#]])

// int64_t (Linux: long, Windows: long long)
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{l|x}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{l|x}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{l|x}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMaxjj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMaxjj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMaxjj{{l|x}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMinjj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMinjj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupSMinjj{{l|x}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{l|x}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{l|x}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{l|x}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{l|x}}(i32 3, i32 2, i64 %[[#]])

// uint64_t (Linux: unsigned long, Windows: unsigned long long)
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseAndjj{{m|y}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseOrjj{{m|y}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformBitwiseXorjj{{m|y}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMaxjj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMaxjj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMaxjj{{m|y}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMinjj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMinjj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupUMinjj{{m|y}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupNonUniformIMuljj{{m|y}}(i32 3, i32 2, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{m|y}}(i32 3, i32 0, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{m|y}}(i32 3, i32 1, i64 %[[#]])
// CHECK: %{{.*}} = call spir_func i64 @_Z[[#]]__spirv_GroupIAddjj{{m|y}}(i32 3, i32 2, i64 %[[#]])

// half
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMaxjjDF16_(i32 3, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMaxjjDF16_(i32 3, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMaxjjDF16_(i32 3, i32 2, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMinjjDF16_(i32 3, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMinjjDF16_(i32 3, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFMinjjDF16_(i32 3, i32 2, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupNonUniformFMuljjDF16_(i32 3, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupNonUniformFMuljjDF16_(i32 3, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupNonUniformFMuljjDF16_(i32 3, i32 2, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFAddjjDF16_(i32 3, i32 0, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFAddjjDF16_(i32 3, i32 1, half %[[#]])
// CHECK: %{{.*}} = call spir_func half @_Z[[#]]__spirv_GroupFAddjjDF16_(i32 3, i32 2, half %[[#]])

// float
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMaxjjf(i32 3, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMaxjjf(i32 3, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMaxjjf(i32 3, i32 2, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMinjjf(i32 3, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMinjjf(i32 3, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFMinjjf(i32 3, i32 2, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupNonUniformFMuljjf(i32 3, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupNonUniformFMuljjf(i32 3, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupNonUniformFMuljjf(i32 3, i32 2, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFAddjjf(i32 3, i32 0, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFAddjjf(i32 3, i32 1, float %[[#]])
// CHECK: %{{.*}} = call spir_func float @_Z[[#]]__spirv_GroupFAddjjf(i32 3, i32 2, float %[[#]])

// double
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMaxjjd(i32 3, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMaxjjd(i32 3, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMaxjjd(i32 3, i32 2, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMinjjd(i32 3, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMinjjd(i32 3, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFMinjjd(i32 3, i32 2, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupNonUniformFMuljjd(i32 3, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupNonUniformFMuljjd(i32 3, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupNonUniformFMuljjd(i32 3, i32 2, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFAddjjd(i32 3, i32 0, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFAddjjd(i32 3, i32 1, double %[[#]])
// CHECK: %{{.*}} = call spir_func double @_Z[[#]]__spirv_GroupFAddjjd(i32 3, i32 2, double %[[#]])
