= SPV_INTEL_fpga_device_global_properties

:source-highlighter: coderay
:coderay-linenums-mode: table

// This section needs to be after the document title.
:doctype: book
:toc2:
:toc: left
:encoding: utf-8
:lang: en

:blank: pass:[ +]

// Set the default source code type in this document to C++,
// for syntax highlighting purposes.  This is needed because
// docbook uses c++ and html5 uses cpp.
:language: {basebackend@docbook:c++:cpp}

// This is necessary for asciidoc, but not for asciidoctor
:cpp: C++

== Name Strings

SPV_INTEL_fpga_device_global_properties

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Headers

== Contributors

Artem Radzikhovskyy, Intel +
Michael Kinsner, Intel +
Joe Garvey, Intel +
Mohammad Fawaz, Intel

== Notice

Copyright (c) 2021 Intel Corporation.  All rights reserved.

== Status

Final Draft

== Version

Built On: {docdate} +
Revision: 1

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.5 Revision 5.

This extension requires SPIR-V 1.0.

== Overview

This extension adds decorations that influence compiler generation of `device_global` structures on FPGA targets.

== Extension Name
To use this extension within a SPIR-V module, the following *OpExtension* must be present in the module:

----
OpExtension "SPV_INTEL_fpga_device_global_properties"
----

== New Capabilities
This extension introduces a new capability:

----
FPGADeviceGlobalPropertiesINTEL
----

== Token Number Assignments

--
[width="40%"]
[cols="70%,30%"]
[grid="rows"]
|====
|FPGADeviceGlobalPropertiesINTEL |6146
|NoCopyINTEL     |6147
|InitViaINTEL     |6148
|ImplementInCSRINTEL     |6149
|==== 
--

== Modifications to the SPIR-V Specification, Version 1.5

=== Decoration

Modify Section 3.20, Decoration, adding these rows to the Decoration table:

--
[options="header"]
|====
2+^| Decoration | Extra Operands | Enabling Capabilities
// --- ROW BREAK ---
| 6147
| *CopyAccessINTEL* + 
Only valid on global variables. 

Controls which memory ports are exposed for use by a generated IP core.

Legal values of _Access_: +
0 [Read] - Only a read port is exposed. +
1 [Write] - Only a write port is exposed. +
2 [Read/Write] - A read/write port is exposed. +
3 [None] - No port is exposed. +
| Literal Number +
_Access_
| *FPGADeviceGlobalPropertiesINTEL*

// --- ROW BREAK ---
| 6148
| *InitViaINTEL* + 
Only valid on global variables.

Controls the event which triggers memory initialization.

Legal values of _Trigger_: +
0 [init on device reprogram] - initialization is performed when the device is programmed. +
1 [init on device reset] - initialization is performed when a reset signal is sent to the device. +

| Literal Number +
_Trigger_
| *FPGADeviceGlobalPropertiesINTEL*

// --- ROW BREAK ---
| 6149
| *ImplementInCSRINTEL* + 
Only valid on global variables.

Controls the interface of this global variable with hardware outside the boundary of the SPIR-V module.

Legal values of _Value_: +
0 [False] - Access to this memory is through a dedicated interface. +
1 [True] - Access to this memory is through a CSR interface shared with the kernel arguments. +

| Literal Number +
_Value_
| *FPGADeviceGlobalPropertiesINTEL*

|====
--

=== Capability

Modify Section 3.31, Capability, adding a row to the Capability table:
--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares
| 6146
| FPGADeviceGlobalPropertiesINTEL
|
|====
--

=== Validation Rules

None.

== Issues

None.

//. Issue.
//+
//--
//*RESOLVED*: Resolution.
//--

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2021-8-9|Artem Radzikhovskyy|*Initial draft*
|======================================== 
