// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals none --version 4
// NOTE: ..., followed by some manual cleanup.

// Had to increase inline threashold for this test to force inline of the vec<>
// math builtins.
// RUN: %clangxx -I %sycl_include -mllvm -inline-threshold=400 -fno-discard-value-names -S -emit-llvm -fno-sycl-instrument-device-code -Xclang -disable-lifetime-markers -O3 -fsycl-device-only %s -o - | FileCheck %s

// Windows/linux have some slight differences in IR generation (function
// arguments passing and long/long long differences/mangling) that could
// complicate test updates while not improving test coverage. Limiting to linux
// should be fine.
// REQUIRES: linux

// This test checks the device code generated for vec<bfloat16> math builtins.
#include <sycl/detail/core.hpp>
#include <sycl/detail/vector_convert.hpp>
#include <sycl/ext/oneapi/experimental/bfloat16_math.hpp>

using namespace sycl;
using namespace sycl::ext::oneapi;
using namespace sycl::ext::oneapi::experimental;

// CHECK-LABEL: define dso_local spir_func void @_Z8TestFMinN4sycl3_V13vecINS0_3ext6oneapi8bfloat16ELi2EEES5_(
// CHECK-SAME: ptr addrspace(4) dead_on_unwind noalias writable writeonly sret(%"class.sycl::_V1::vec") align 4 captures(none) initializes((0, 4)) [[AGG_RESULT:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec") align 4 captures(none) [[A:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec") align 4 captures(none) [[B:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {{.*}}{
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I8_I:%.*]] = alloca <2 x float>, align 8
// CHECK-NEXT:    [[DST_I_I_I_I9_I:%.*]] = alloca [2 x %"class.sycl::_V1::ext::oneapi::bfloat16"], align 2
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I2_I:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[DST_I_I_I_I3_I:%.*]] = alloca [2 x float], align 4
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I_I:%.*]] = alloca <2 x i16>, align 4
// CHECK-NEXT:    [[DST_I_I_I_I_I:%.*]] = alloca [2 x float], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <2 x i16>, ptr [[A]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i16>, ptr [[B]], align 4
// CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META11:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META14:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META14]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <2 x i16> [[TMP0]], ptr [[VEC_ADDR_I_I_I_I_I]], align 4, !tbaa [[TBAA17:![0-9]+]], !noalias [[META14]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec2(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I_I]]) #[[ATTR5:[0-9]+]], !noalias [[META14]]
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x float>, ptr [[DST_I_I_I_I_I]], align 4, !tbaa [[TBAA17]], !noalias [[META14]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META14]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META14]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META18:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META18]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I4_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I2_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I5_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I3_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <2 x i16> [[TMP1]], ptr [[VEC_ADDR_I_I_I_I2_I]], align 4, !tbaa [[TBAA17]], !noalias [[META18]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec2(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I4_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I5_I]]) #[[ATTR5]], !noalias [[META18]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <2 x float>, ptr [[DST_I_I_I_I3_I]], align 4, !tbaa [[TBAA17]], !noalias [[META18]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META18]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META18]]
// CHECK-NEXT:    [[CALL2_I_I:%.*]] = call spir_func noundef <2 x float> @_Z16__spirv_ocl_fminDv2_fS_(<2 x float> noundef [[TMP2]], <2 x float> noundef [[TMP3]]) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META21:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I8_I]]), !noalias [[META24:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I9_I]]), !noalias [[META24]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I10_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I8_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I11_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I9_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <2 x float> [[CALL2_I_I]], ptr [[VEC_ADDR_I_I_I_I8_I]], align 8, !tbaa [[TBAA17]], !noalias [[META24]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertFToBF16INTELVec2(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I10_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I11_I]]) #[[ATTR5]], !noalias [[META24]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[DST_I_I_I_I9_I]], align 2, !tbaa [[TBAA17]], !noalias [[META24]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I8_I]]), !noalias [[META24]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I9_I]]), !noalias [[META24]]
// CHECK-NEXT:    store i32 [[TMP4]], ptr addrspace(4) [[AGG_RESULT]], align 4, !alias.scope [[META24]]
// CHECK-NEXT:    ret void
//
SYCL_EXTERNAL auto TestFMin(vec<bfloat16, 2> a, vec<bfloat16, 2> b) {
  return experimental::fmin(a, b);
}

// CHECK-LABEL: define dso_local spir_func void @_Z8TestFMaxN4sycl3_V13vecINS0_3ext6oneapi8bfloat16ELi3EEES5_(
// CHECK-SAME: ptr addrspace(4) dead_on_unwind noalias writable writeonly sret(%"class.sycl::_V1::vec.70") align 8 captures(none) initializes((0, 8)) [[AGG_RESULT:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.70") align 8 captures(none) [[A:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.70") align 8 captures(none) [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {{.*}}{
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I14_I:%.*]] = alloca <3 x float>, align 16
// CHECK-NEXT:    [[DST_I_I_I_I15_I:%.*]] = alloca [4 x %"class.sycl::_V1::ext::oneapi::bfloat16"], align 2
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I2_I:%.*]] = alloca <3 x i16>, align 8
// CHECK-NEXT:    [[DST_I_I_I_I3_I:%.*]] = alloca [4 x float], align 4
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I_I:%.*]] = alloca <3 x i16>, align 8
// CHECK-NEXT:    [[DST_I_I_I_I_I:%.*]] = alloca [4 x float], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i16>, ptr [[A]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i16>, ptr [[B]], align 8
// CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META25:![0-9]+]])
// CHECK-NEXT:    [[EXTRACTVEC_I_I_I:%.*]] = shufflevector <4 x i16> [[TMP0]], <4 x i16> poison, <3 x i32> <i32 0, i32 1, i32 2>
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META28:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META28]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[EXTRACTVEC_I_I_I_I_I:%.*]] = shufflevector <3 x i16> [[EXTRACTVEC_I_I_I]], <3 x i16> <i16 undef, i16 poison, i16 poison>, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    store <4 x i16> [[EXTRACTVEC_I_I_I_I_I]], ptr [[VEC_ADDR_I_I_I_I_I]], align 8, !tbaa [[TBAA17]], !noalias [[META28]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec3(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I_I]]) #[[ATTR5]], !noalias [[META28]]
// CHECK-NEXT:    [[LOADVECN_I_I_I_I_I_I:%.*]] = load <4 x float>, ptr [[DST_I_I_I_I_I]], align 4, !noalias [[META28]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META28]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META28]]
// CHECK-NEXT:    [[EXTRACTVEC_I_I5_I:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> poison, <3 x i32> <i32 0, i32 1, i32 2>
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META31:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META31]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I6_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I2_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I7_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I3_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[EXTRACTVEC_I_I_I_I8_I:%.*]] = shufflevector <3 x i16> [[EXTRACTVEC_I_I5_I]], <3 x i16> <i16 undef, i16 poison, i16 poison>, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    store <4 x i16> [[EXTRACTVEC_I_I_I_I8_I]], ptr [[VEC_ADDR_I_I_I_I2_I]], align 8, !tbaa [[TBAA17]], !noalias [[META31]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec3(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I6_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I7_I]]) #[[ATTR5]], !noalias [[META31]]
// CHECK-NEXT:    [[LOADVECN_I_I_I_I_I9_I:%.*]] = load <4 x float>, ptr [[DST_I_I_I_I3_I]], align 4, !noalias [[META31]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META31]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META31]]
// CHECK-NEXT:    [[EXTRACTVEC_I_I_I_I:%.*]] = shufflevector <4 x float> [[LOADVECN_I_I_I_I_I_I]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
// CHECK-NEXT:    [[EXTRACTVEC_I_I4_I_I:%.*]] = shufflevector <4 x float> [[LOADVECN_I_I_I_I_I9_I]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
// CHECK-NEXT:    [[CALL2_I_I:%.*]] = call spir_func noundef <3 x float> @_Z16__spirv_ocl_fmaxDv3_fS_(<3 x float> noundef [[EXTRACTVEC_I_I_I_I]], <3 x float> noundef [[EXTRACTVEC_I_I4_I_I]]) #[[ATTR6]]
// CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META34:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I14_I]]), !noalias [[META37:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I15_I]]), !noalias [[META37]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I18_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I14_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I19_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I15_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[EXTRACTVEC_I_I_I_I20_I:%.*]] = shufflevector <3 x float> [[CALL2_I_I]], <3 x float> <float undef, float poison, float poison>, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    store <4 x float> [[EXTRACTVEC_I_I_I_I20_I]], ptr [[VEC_ADDR_I_I_I_I14_I]], align 16, !tbaa [[TBAA17]], !noalias [[META37]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertFToBF16INTELVec3(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I18_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I19_I]]) #[[ATTR5]], !noalias [[META37]]
// CHECK-NEXT:    [[LOADVECN_I_I_I_I_I21_I:%.*]] = load <4 x i16>, ptr [[DST_I_I_I_I15_I]], align 2, !noalias [[META37]]
// CHECK-NEXT:    [[EXTRACTVEC_I_I_I_I_I22_I:%.*]] = shufflevector <4 x i16> [[LOADVECN_I_I_I_I_I21_I]], <4 x i16> poison, <3 x i32> <i32 0, i32 1, i32 2>
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I14_I]]), !noalias [[META37]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I15_I]]), !noalias [[META37]]
// CHECK-NEXT:    [[EXTRACTVEC_I23_I:%.*]] = shufflevector <3 x i16> [[EXTRACTVEC_I_I_I_I_I22_I]], <3 x i16> <i16 undef, i16 poison, i16 poison>, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    store <4 x i16> [[EXTRACTVEC_I23_I]], ptr addrspace(4) [[AGG_RESULT]], align 8, !alias.scope [[META37]]
// CHECK-NEXT:    ret void
//
SYCL_EXTERNAL auto TestFMax(vec<bfloat16, 3> a, vec<bfloat16, 3> b) {
  return experimental::fmax(a, b);
}

// CHECK-LABEL: define dso_local spir_func void @_Z9TestIsNanN4sycl3_V13vecINS0_3ext6oneapi8bfloat16ELi4EEE(
// CHECK-SAME: ptr addrspace(4) dead_on_unwind noalias writable writeonly sret(%"class.sycl::_V1::vec.146") align 8 captures(none) initializes((0, 8)) [[AGG_RESULT:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.183") align 8 captures(none) [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {{.*}}{
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I_I:%.*]] = alloca <4 x i16>, align 8
// CHECK-NEXT:    [[DST_I_I_I_I_I:%.*]] = alloca [4 x float], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i16>, ptr [[A]], align 8
// CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META38:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META41:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META41]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <4 x i16> [[TMP0]], ptr [[VEC_ADDR_I_I_I_I_I]], align 8, !tbaa [[TBAA17]], !noalias [[META41]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec4(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I_I]]) #[[ATTR5]], !noalias [[META41]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[DST_I_I_I_I_I]], align 4, !tbaa [[TBAA17]], !noalias [[META41]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META41]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META41]]
// CHECK-NEXT:    [[CALL_I_I_I_I:%.*]] = call spir_func noundef <4 x i8> @_Z13__spirv_IsNanDv4_f(<4 x float> noundef [[TMP1]]) #[[ATTR6]]
// CHECK-NEXT:    [[CALL_I_I_I_I_I_I:%.*]] = call spir_func noundef <4 x i32> @_Z22__spirv_SConvert_Rint4Dv4_a(<4 x i8> noundef [[CALL_I_I_I_I]]) #[[ATTR6]]
// CHECK-NEXT:    [[CALL_I_I_I2_I:%.*]] = call spir_func noundef <4 x i16> @_Z24__spirv_SConvert_Rshort4Dv4_i(<4 x i32> noundef [[CALL_I_I_I_I_I_I]]) #[[ATTR6]]
// CHECK-NEXT:    store <4 x i16> [[CALL_I_I_I2_I]], ptr addrspace(4) [[AGG_RESULT]], align 8, !alias.scope [[META44:![0-9]+]]
// CHECK-NEXT:    ret void
//
SYCL_EXTERNAL auto TestIsNan(vec<bfloat16, 4> a) {
  return experimental::isnan(a);
}

// CHECK-LABEL: define dso_local spir_func void @_Z8TestFabsN4sycl3_V13vecINS0_3ext6oneapi8bfloat16ELi8EEE(
// CHECK-SAME: ptr addrspace(4) dead_on_unwind noalias writable writeonly sret(%"class.sycl::_V1::vec.335") align 16 captures(none) initializes((0, 16)) [[AGG_RESULT:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.335") align 16 captures(none) [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {{.*}}{
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I2_I:%.*]] = alloca <8 x float>, align 32
// CHECK-NEXT:    [[DST_I_I_I_I3_I:%.*]] = alloca [8 x %"class.sycl::_V1::ext::oneapi::bfloat16"], align 2
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DST_I_I_I_I_I:%.*]] = alloca [8 x float], align 4
// CHECK-NEXT:    [[AGG_TMP_SROA_0_SROA_0_0_COPYLOAD:%.*]] = load <8 x i16>, ptr [[A]], align 16
// CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META47:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META50:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META50]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <8 x i16> [[AGG_TMP_SROA_0_SROA_0_0_COPYLOAD]], ptr [[VEC_ADDR_I_I_I_I_I]], align 16, !tbaa [[TBAA17]], !noalias [[META50]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec8(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I_I]]) #[[ATTR5]], !noalias [[META50]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[DST_I_I_I_I_I]], align 4, !tbaa [[TBAA17]], !noalias [[META50]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META50]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META50]]
// CHECK-NEXT:    [[CALL1_I_I:%.*]] = call spir_func noundef <8 x float> @_Z16__spirv_ocl_fabsDv8_f(<8 x float> noundef [[TMP0]]) #[[ATTR6]]
// CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META53:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META56:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META56]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I4_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I2_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I5_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I3_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <8 x float> [[CALL1_I_I]], ptr [[VEC_ADDR_I_I_I_I2_I]], align 32, !tbaa [[TBAA17]], !noalias [[META56]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertFToBF16INTELVec8(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I4_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I5_I]]) #[[ATTR5]], !noalias [[META56]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[DST_I_I_I_I3_I]], align 2, !tbaa [[TBAA17]], !noalias [[META56]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META56]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META56]]
// CHECK-NEXT:    store <8 x i16> [[TMP1]], ptr addrspace(4) [[AGG_RESULT]], align 16, !alias.scope [[META56]]
// CHECK-NEXT:    ret void
//
SYCL_EXTERNAL auto TestFabs(vec<bfloat16, 8> a) {
  return experimental::fabs(a);
}

// CHECK-LABEL: define dso_local spir_func void @_Z8TestCeilN4sycl3_V13vecINS0_3ext6oneapi8bfloat16ELi8EEE(
// CHECK-SAME: ptr addrspace(4) dead_on_unwind noalias writable writeonly sret(%"class.sycl::_V1::vec.335") align 16 captures(none) initializes((0, 16)) [[AGG_RESULT:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.335") align 16 captures(none) [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {{.*}}{
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I2_I:%.*]] = alloca <8 x float>, align 32
// CHECK-NEXT:    [[DST_I_I_I_I3_I:%.*]] = alloca [8 x %"class.sycl::_V1::ext::oneapi::bfloat16"], align 2
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DST_I_I_I_I_I:%.*]] = alloca [8 x float], align 4
// CHECK-NEXT:    [[AGG_TMP_SROA_0_SROA_0_0_COPYLOAD:%.*]] = load <8 x i16>, ptr [[A]], align 16
// CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META57:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META60:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META60]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <8 x i16> [[AGG_TMP_SROA_0_SROA_0_0_COPYLOAD]], ptr [[VEC_ADDR_I_I_I_I_I]], align 16, !tbaa [[TBAA17]], !noalias [[META60]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec8(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I_I]]) #[[ATTR5]], !noalias [[META60]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <8 x float>, ptr [[DST_I_I_I_I_I]], align 4, !tbaa [[TBAA17]], !noalias [[META60]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META60]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META60]]
// CHECK-NEXT:    [[CALL1_I_I:%.*]] = call spir_func noundef <8 x float> @_Z16__spirv_ocl_ceilDv8_f(<8 x float> noundef [[TMP0]]) #[[ATTR6]]
// CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META63:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META66:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META66]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I4_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I2_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I5_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I3_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <8 x float> [[CALL1_I_I]], ptr [[VEC_ADDR_I_I_I_I2_I]], align 32, !tbaa [[TBAA17]], !noalias [[META66]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertFToBF16INTELVec8(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I4_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I5_I]]) #[[ATTR5]], !noalias [[META66]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[DST_I_I_I_I3_I]], align 2, !tbaa [[TBAA17]], !noalias [[META66]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I2_I]]), !noalias [[META66]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I3_I]]), !noalias [[META66]]
// CHECK-NEXT:    store <8 x i16> [[TMP1]], ptr addrspace(4) [[AGG_RESULT]], align 16, !alias.scope [[META66]]
// CHECK-NEXT:    ret void
//
SYCL_EXTERNAL auto TestCeil(vec<bfloat16, 8> a) {
  return experimental::ceil(a);
}

// CHECK-LABEL: define dso_local spir_func void @_Z7TestFMAN4sycl3_V13vecINS0_3ext6oneapi8bfloat16ELi16EEES5_S5_(
// CHECK-SAME: ptr addrspace(4) dead_on_unwind noalias writable writeonly sret(%"class.sycl::_V1::vec.411") align 32 captures(none) initializes((0, 32)) [[AGG_RESULT:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.411") align 32 captures(none) [[A:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.411") align 32 captures(none) [[B:%.*]], ptr noundef readonly byval(%"class.sycl::_V1::vec.411") align 32 captures(none) [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {{.*}}{
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I14_I:%.*]] = alloca <16 x float>, align 64
// CHECK-NEXT:    [[DST_I_I_I_I15_I:%.*]] = alloca [16 x %"class.sycl::_V1::ext::oneapi::bfloat16"], align 2
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I7_I:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[DST_I_I_I_I8_I:%.*]] = alloca [16 x float], align 4
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I3_I:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[DST_I_I_I_I4_I:%.*]] = alloca [16 x float], align 4
// CHECK-NEXT:    [[VEC_ADDR_I_I_I_I_I:%.*]] = alloca <16 x i16>, align 32
// CHECK-NEXT:    [[DST_I_I_I_I_I:%.*]] = alloca [16 x float], align 4
// CHECK-NEXT:    [[AGG_TMP_SROA_0_SROA_0_0_COPYLOAD:%.*]] = load <16 x i16>, ptr [[A]], align 32
// CHECK-NEXT:    [[AGG_TMP1_SROA_0_SROA_0_0_COPYLOAD:%.*]] = load <16 x i16>, ptr [[B]], align 32
// CHECK-NEXT:    [[AGG_TMP2_SROA_0_SROA_0_0_COPYLOAD:%.*]] = load <16 x i16>, ptr [[C]], align 32
// CHECK-NEXT:    tail call void @llvm.experimental.noalias.scope.decl(metadata [[META67:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META70:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META70]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <16 x i16> [[AGG_TMP_SROA_0_SROA_0_0_COPYLOAD]], ptr [[VEC_ADDR_I_I_I_I_I]], align 32, !tbaa [[TBAA17]], !noalias [[META70]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec16(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I_I]]) #[[ATTR5]], !noalias [[META70]]
// CHECK-NEXT:    [[TMP0:%.*]] = load <16 x float>, ptr [[DST_I_I_I_I_I]], align 4, !tbaa [[TBAA17]], !noalias [[META70]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I_I]]), !noalias [[META70]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I_I]]), !noalias [[META70]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I3_I]]), !noalias [[META73:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I4_I]]), !noalias [[META73]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I5_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I3_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I6_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I4_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <16 x i16> [[AGG_TMP1_SROA_0_SROA_0_0_COPYLOAD]], ptr [[VEC_ADDR_I_I_I_I3_I]], align 32, !tbaa [[TBAA17]], !noalias [[META73]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec16(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I5_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I6_I]]) #[[ATTR5]], !noalias [[META73]]
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x float>, ptr [[DST_I_I_I_I4_I]], align 4, !tbaa [[TBAA17]], !noalias [[META73]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I3_I]]), !noalias [[META73]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I4_I]]), !noalias [[META73]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I7_I]]), !noalias [[META76:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I8_I]]), !noalias [[META76]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I9_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I7_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I10_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I8_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <16 x i16> [[AGG_TMP2_SROA_0_SROA_0_0_COPYLOAD]], ptr [[VEC_ADDR_I_I_I_I7_I]], align 32, !tbaa [[TBAA17]], !noalias [[META76]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertBF16ToFINTELVec16(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I9_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I10_I]]) #[[ATTR5]], !noalias [[META76]]
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x float>, ptr [[DST_I_I_I_I8_I]], align 4, !tbaa [[TBAA17]], !noalias [[META76]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I7_I]]), !noalias [[META76]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I8_I]]), !noalias [[META76]]
// CHECK-NEXT:    [[CALL3_I_I:%.*]] = call spir_func noundef <16 x float> @_Z15__spirv_ocl_fmaDv16_fS_S_(<16 x float> noundef [[TMP0]], <16 x float> noundef [[TMP1]], <16 x float> noundef [[TMP2]]) #[[ATTR6]]
// CHECK-NEXT:    call void @llvm.experimental.noalias.scope.decl(metadata [[META79:![0-9]+]])
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[VEC_ADDR_I_I_I_I14_I]]), !noalias [[META82:![0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[DST_I_I_I_I15_I]]), !noalias [[META82]]
// CHECK-NEXT:    [[VEC_ADDR_ASCAST_I_I_I_I16_I:%.*]] = addrspacecast ptr [[VEC_ADDR_I_I_I_I14_I]] to ptr addrspace(4)
// CHECK-NEXT:    [[DST_ASCAST_I_I_I_I17_I:%.*]] = addrspacecast ptr [[DST_I_I_I_I15_I]] to ptr addrspace(4)
// CHECK-NEXT:    store <16 x float> [[CALL3_I_I]], ptr [[VEC_ADDR_I_I_I_I14_I]], align 64, !tbaa [[TBAA17]], !noalias [[META82]]
// CHECK-NEXT:    call spir_func void @__devicelib_ConvertFToBF16INTELVec16(ptr addrspace(4) noundef [[VEC_ADDR_ASCAST_I_I_I_I16_I]], ptr addrspace(4) noundef [[DST_ASCAST_I_I_I_I17_I]]) #[[ATTR5]], !noalias [[META82]]
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i16>, ptr [[DST_I_I_I_I15_I]], align 2, !tbaa [[TBAA17]], !noalias [[META82]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[VEC_ADDR_I_I_I_I14_I]]), !noalias [[META82]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[DST_I_I_I_I15_I]]), !noalias [[META82]]
// CHECK-NEXT:    store <16 x i16> [[TMP3]], ptr addrspace(4) [[AGG_RESULT]], align 32, !alias.scope [[META82]]
// CHECK-NEXT:    ret void
//
SYCL_EXTERNAL auto TestFMA(vec<bfloat16, 16> a, vec<bfloat16, 16> b,
                           vec<bfloat16, 16> c) {
  return experimental::fma(a, b, c);
}
