:fp4_extension_name: SPV_INTEL_float4
:fp4_encoding_name: Float4E2M1INTEL

= Mini-float Types and Conversions Environment Specification

== Implementation Notes

This document provides list of supported conversions for types and instructions
added by the *SPV_INTEL_fp_conversions*, *SPV_EXT_float8*, *SPV_INTEL_int4*,
*{fp4_extension_name}* extensions for Level-Zero and OpenCL Environments for
Intel platforms.

NOTE: These implementation notes will eventually be moved to client API specifications.

The following conversions are supported for *OpFConvert*.

 * For conversions to the fp8 types *Float8E4M3EXT* and *Float8E5M2EXT*, use the *SaturatedToLargestFloat8NormalConversionEXT* decoration to control whether the conversions are saturated.
 * For conversions to the fp4 type *{fp4_encoding_name}*, the conversion is always saturated to the nearest representable value.
 * For conversions to the *BFloat16KHR* type, the only supported rounding mode is *RTE* (round to nearest even), and is the default rounding mode.
 * For conversions to the fp8 types *Float8E4M3EXT* and *Float8E5M2EXT*, the only supported rounding mode is *RTE* (round to nearest even), and is the default rounding mode.
 * For conversions to the fp4 type *{fp4_encoding_name}*, the only supported rounding mode is *RTE* (round to nearest even), and is the default rounding mode.

[cols="9*^.^", width="100%"]
|====
2.2+| *OpFConvert*: 7+| To:
| 64-bit *IEEE754* | 32-bit *IEEE754* | 16-bit *IEEE754* | *BFloat16KHR* | *Float8E4M3EXT* | *Float8E5M2EXT* | *{fp4_encoding_name}*
.7+| From:
//                       fp64  fp32  fp16  bf16  e4m3  e5m2  e2m1
| 64-bit *IEEE754*      |  -  | Yes | Yes |     |     |     |
| 32-bit *IEEE754*      | Yes |  -  | Yes | Yes |     |     |
| 16-bit *IEEE754*      | Yes | Yes |  -  | Yes | Yes | Yes | Yes
| *BFloat16KHR*         |     | Yes | Yes |  -  | Yes | Yes | Yes
| *Float8E4M3EXT*       |     |     | Yes | Yes |  -  |     |
| *Float8E5M2EXT*       |     |     | Yes | Yes |     |  -  |
| *{fp4_encoding_name}* |     |     | Yes | Yes | Yes | Yes |  -
|====

The following conversions are supported for *OpStochasticRoundFToFINTEL*.

 * For conversions to the fp8 types *Float8E4M3EXT* and *Float8E5M2EXT*, use the *SaturatedToLargestFloat8NormalConversionEXT* decoration to control whether the conversions are saturated.
 * For conversions to the fp4 type *{fp4_encoding_name}*, the conversion is always saturated to the nearest representable value.
 * For conversions to the fp8 types *Float8E4M3EXT* and *Float8E5M2EXT*, the only supported rounding mode is *RTE* (round to nearest even), and is the default rounding mode.
 * For conversions to the fp4 type *{fp4_encoding_name}*, the only supported rounding mode is *RTE* (round to nearest even), and is the default rounding mode.

[cols="9*^.^", width="100%"]
|====
2.2+| *OpStochasticRoundFToFINTEL*: 7+| To:
| 64-bit *IEEE754* | 32-bit *IEEE754* | 16-bit *IEEE754* | *BFloat16KHR* | *Float8E4M3EXT* | *Float8E5M2EXT* | *{fp4_encoding_name}*
.7+| From:
//                       fp64  fp32  fp16  bf16  e4m3  e5m2  e2m1
| 64-bit *IEEE754*      |  -  |     |     |     |     |     |
| 32-bit *IEEE754*      |     |  -  | Yes |     |     |     |
| 16-bit *IEEE754*      |     |     |  -  |     | Yes | Yes | Yes
| *BFloat16KHR*         |     |     |     |  -  | Yes | Yes | Yes
| *Float8E4M3EXT*       |     |     |     |     |  -  |     |
| *Float8E5M2EXT*       |     |     |     |     |     |  -  |
| *{fp4_encoding_name}* |     |     |     |     |     |     |  -
|====

The following conversions are supported for *OpClampConvertFToSINTEL* and *OpClampStochasticRoundFToSINTEL*.

* For these conversions, the only supported rounding mode is *RTE* (round to nearest even), and is the default rounding mode.

[cols="3*^.^", width="20%"]
|====
2.2+| *OpClampConvertFToSINTEL* and +
*OpClampStochasticRoundFToSINTEL*: 1+| To:
| 4-bit *Integer*
.7+| From:
//                       int4
| 64-bit *IEEE754*      |
| 32-bit *IEEE754*      |
| 16-bit *IEEE754*      | Yes
| *BFloat16KHR*         | Yes
| *Float8E4M3EXT*       |
| *Float8E5M2EXT*       |
| *{fp4_encoding_name}* |
|====

NOTE: There is currently no support for saturated conversions from 32-bit *IEEE754* to 16-bit *IEEE754* - is this OK?

=== Mappings from Prior Names

This section describes mappings from prior versions of this extension and related extensions to the new names:

NOTE: This mapping is informative and may be removed before publishing.

[cols="2*", width="100%"]
[options="header"]
|====
| Prior Name: | New Name:

// OpClampConvertFToFINTEL:

| *OpClampConvertFToFINTEL* +
to *Float8E4M3EXT* or *Float8E5M2EXT*
| *OpFConvert* +
with *SaturatedToLargestFloat8NormalConversionEXT*

| *OpClampConvertFToFINTEL* +
to *{fp4_encoding_name}*
| *OpFConvert* +
(saturation is unconditional to *{fp4_encoding_name}*)

| *OpClampConvertFToFINTEL* +
to 16-bit *IEEE754*
| Not supported - is this OK?

// OpClampStochasticRoundFToFINTEL:

| *OpClampStochasticRoundFToFINTEL* +
to *Float8E4M3EXT* or *Float8E5M2EXT*
| *OpStochasticRoundFToFINTEL* +
with *SaturatedToLargestFloat8NormalConversionEXT*

| *OpClampStochasticRoundFToFINTEL* +
to *{fp4_encoding_name}*
| *OpStochasticRoundFToFINTEL* +
(saturation is unconditional to *{fp4_encoding_name}*)

| *OpClampStochasticRoundFToFINTEL* +
to 16-bit *IEEE754*
| Not supported - is this OK?

|====

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2024-06-15|Dmitry Sidorov|Initial revision
|1|2026-05-28|Ben Ashbaugh|More preparations for publication
|========================================
