:extension_name: SPV_INTEL_float4

:hf4_matrix_capability_name: Float4E2M1CooperativeMatrixINTEL
:hf4_matrix_capability_token: 6213
:hf4_encoding_name: Float4E2M1EXT

:khr_matrix_capability_name: CooperativeMatrixKHR
:float4ext_capability_name: Float4EXT

:joint_matrix_url:  https://https://github.com/intel/llvm/tree/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_joint_matrix.asciidoc
:fp_conv_url: https://github.com/intel/llvm/tree/sycl/sycl/doc/design/spirv-extensions/SPV_INTEL_fp_conversions.asciidoc
:coop_matrix_url: https://github.khronos.org/SPIRV-Registry/extensions/KHR/SPV_KHR_cooperative_matrix.html
:bfloat16_url: https://github.khronos.org/SPIRV-Registry/extensions/KHR/SPV_KHR_bfloat16.html
:fp8_url: https://github.khronos.org/SPIRV-Registry/extensions/EXT/SPV_EXT_float8.html

{extension_name}
================


== Name Strings

{extension_name}

== Contributors

- Dmitry Sidorov, Intel +
- Victor Mustya, Intel +
- Ben Ashbaugh, Intel +
- Dounia Khaldi, Intel +
- Joe Garvey, Intel +
- Greg Lueck, Intel +
- Pawel Jurek, Intel +

Notice
------

Copyright (c) 2025 Intel Corporation. All rights reserved.

Status
------

* Working Draft

This is a preview extension specification, intended to provide early access to
a feature for review and community feedback. When the feature matures, this
specification may be released as a formal extension.

Because the interfaces defined by this specification are not final and are
subject to change they are not intended to be used by shipping software
products. If you are interested in using this feature in your software product,
please let us know!

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2026-07-02
| Revision           | 3
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.6 Revision 4.

This extension interacts with {coop_matrix_url}[*SPV_KHR_cooperative_matrix*] extension.

This extension interacts with {joint_matrix_url}[*SPV_INTEL_joint_matrix*] extension.

This extension interacts with {bfloat16_url}[*SPV_KHR_bfloat16*] extension.

This extension interacts with {fp8_url}[*SPV_EXT_float8*] extension.

This extension interacts with {fp_conv_url}[*SPV_INTEL_fp_conversions*] extension.

This extension depends on the *SPV_EXT_ocp_microscaling_types* extension, which
provides the *Float4E2M1EXT* encoding that this extension uses as a
cooperative-matrix component type.

This extension requires SPIR-V 1.0.

Overview
--------

The `FP4E2M1` floating-point type, which has one sign bit, two exponent bits and
one mantissa bit, is defined by the multi-vendor *SPV_EXT_ocp_microscaling_types*
extension as the *Float4E2M1EXT* encoding.

This extension enables that type to be used as an *OpTypeCooperativeMatrixKHR*
component type, for which the microscaling extension has no analog.

== Modifications to the SPIR-V Specification, Version 1.6

The FP4 (E2M1) type is represented with the *{hf4_encoding_name}* floating-point
encoding defined by the *SPV_EXT_ocp_microscaling_types* extension.
This extension adds the capability to use that type as an *OpTypeCooperativeMatrixKHR*
component type, for which the microscaling extension has no analog.

=== Capabilities

Modify Section 3.31, Capability, adding a row to the Capability table:

--
[options="header"]
|====
2+^| Capability ^| Implicitly Declares
| {hf4_matrix_capability_token} | *{hf4_matrix_capability_name}* +
Uses a cooperative matrix with a _Component Type_ of *OpTypeFloat* with the
*{hf4_encoding_name}* encoding. | *{float4ext_capability_name}*, *{khr_matrix_capability_name}*
|====
--

=== Instructions

==== 3.49.6. Type-Declaration Instructions

Add the following requirement to *OpTypeCooperativeMatrixKHR*:

If _Component Type_ has a *{hf4_encoding_name}* encoding then *{hf4_matrix_capability_name}* must be declared.

Validation Rules
~~~~~~~~~~~~~~~~

The *SPV_EXT_ocp_microscaling_types* extension restricts the instructions that a
*{hf4_encoding_name}*-encoded object may be used with, and does not permit the
cooperative-matrix instructions.
This extension additionally permits a cooperative matrix whose _Component Type_
has the *{hf4_encoding_name}* encoding to be used with the following instructions:

  * OpCooperativeMatrixMulAddKHR
  * OpCooperativeMatrixMulAddScaledINTEL

=== Issues

-

Revision History
----------------

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2024-06-15|Dmitry Sidorov|Initial revision
|2|2025-10-24|Dmitry Sidorov|Prepare to publish
|3|2026-07-02|Viktoria Maksimova|Represent the FP4E2M1 type with the SPV_EXT_ocp_microscaling_types Float4E2M1EXT encoding; narrow this extension to enabling that type as a cooperative-matrix component type
|========================================
