:extension_name: SPV_INTEL_fp_conversions

:f2f_capability_name: FloatConversionsFtoFINTEL
:f2f_capability_token: 6215
:f2s_capability_name: FloatConversionsFtoSINTEL
// Note: OK to reuse 6216 due to different token namespaces for capabilities and instructions:
:f2s_capability_token: 6216
//:OpClampConvertFToFINTEL_token: 6216 - no longer needed - reused
:OpClampConvertFToSINTEL_token: 6424
:OpStochasticRoundFToFINTEL_token: 6217
//:OpClampStochasticRoundFToFINTEL_token: 6218 - no longer needed - can be recycled if needed
:OpClampStochasticRoundFToSINTEL_token: 6219

= {extension_name}

== Name Strings

{extension_name}

== Contact

To report problems with this extension, please open a new issue at:

https://github.com/KhronosGroup/SPIRV-Registry

== Contributors

- Dmitry Sidorov, Intel +
- Victor Mustya, Intel +
- Ben Ashbaugh, Intel +
- Dounia Khaldi, Intel +
- Joe Garvey, Intel +
- Greg Lueck, Intel +
- Pawel Jurek, Intel +
- John Lu, Intel +
- Eyal Radiano, Intel +
- Mateusz Garbowski, Intel +

== Notice

Copyright (c) 2026 Intel Corporation. All rights reserved.

== Status

* Working Draft

This is a preview extension specification, intended to provide early access to
a feature for review and community feedback. When the feature matures, this
specification may be released as a formal extension.

Because the interfaces defined by this specification are not final and are
subject to change they are not intended to be used by shipping software
products. If you are interested in using this feature in your software product,
please let us know!

== Version

[width="40%",cols="25,25"]
|========================================
| Last Modified Date | 2025-05-28
| Revision           | 1
|========================================

== Dependencies

This extension is written against the SPIR-V Specification,
Version 1.6 Revision 7.

This extension requires SPIR-V 1.0.

== Overview

This extension adds additional instructions to convert floating-point types with stochastic rounding.
Stochastic rounding replaces deterministic rounding behavior with a stochastic (probabilistic) rounding behavior.
Stochastic rounding is important for certain numerical algorithms, particularly those relying on small floating-point types.

== Modifications to the SPIR-V Specification, Version 1.6

=== Capabilities

Modify Section 3.2.30, Capability, adding rows to the Capability table:

--
[cols="^.^2,16,15",options="header"]
|====
2+^.^| Capability | Implicitly Declares
| {f2f_capability_token} | *{f2f_capability_name}* +
Uses *OpStochasticRoundFToFINTEL* instructions.
|
| {f2s_capability_token} | *{f2s_capability_name}* +
Uses *OpClampConvertFToSINTEL* or *OpClampStochasticRoundFToSINTEL* instructions.
|
|====
--

=== Instructions

==== 3.42.11. Conversion Instructions

[cols="1a,1,3*3",width="100%"]
|=====
4+|[[OpClampConvertFToSINTEL]]*OpClampConvertFToSINTEL* +
 +
Converts value numerically from floating point to signed integer by rounding to the nearest even. +
 +
In case of NaN or overflow, the result is saturated to the nearest representable value
of _Result Type_. +
 +
_Result Type_ is the type of the converted object, it must be a scalar or
vector of _integer type_. +
 +
_Value_ must be a scalar or vector of _floating-point type_.
It must have the same number of components as _Result Type_. +
 +
Results are computed per component. +
 +
1+|Capability: +
*{f2s_capability_name}*
1+| 4 | {OpClampConvertFToSINTEL_token}
| _<id>_ +
_Result Type_
| _Result <id>_
| _<id>_ +
_Value_
|=====

[cols="1a,1,5*",width="100%"]
|=====
6+|[[OpStochasticRoundFToFINTEL]]*OpStochasticRoundFToFINTEL* +
 +
Convert value numerically from one floating point width to another using stochastic rounding. +
 +
Stochastic rounding is performed by adding a pseudo-random bias value to the mantissa
of the converted value as follows: The bias is first added to the mantissa of the converted value.
If this causes the mantissa to overflow, then the exponent of the converted value
is increased by 1 and the mantissa bits are shifted right. The value is then converted
to the _Result Type_, rounding towards zero. If the exponent overflows when converting
to the _Result Type_, the result of the conversion is +/- Inf. If _Result Type_ doesn't have
an Inf representation, then the result saturates to the nearest representable value
of the type. +
 +
As described above, each input requires a bias value in order to perform the conversion.
These bias values are generated by executing an implementation-defined algorithm
that produces pseudo-random values that uses _Seed_ as a starting point. This algorithm is
guaranteed to produce repeatable bias values when the same value is passed for _Seed_. +
 +
The instruction also returns a value in _Next Seed_, which client code can use to generate
good quality random biases. If the client intends to call *OpStochasticRoundFToFINTEL*
again from the same kernel invocation, it should use this value as a new seed that it
passes as _Seed_ in that next call. +
 +
_Result Type_ is the type of the converted value and must be a scalar or
vector of _floating-point type_. +
 +
_Value_ must be a scalar or vector of _floating-point type_. It must have a wider range
than the _Result Type_ and it must have the same number of components as _Result Type_. +
 +
_Seed_ must be a 32-bit scalar _integer type_. +
 +
_Next Seed_ must be of a _pointer type_ with *Function* storage class and 32-bit scalar _integer_ element type. +
 +
Results are computed per component. +
1+|Capability: +
*{f2f_capability_name}*
1+| 4+ | {OpStochasticRoundFToFINTEL_token}
| _<id>_ +
_Result Type_
| _Result <id>_
| _<id>_ +
_Value_
| _<id>_ +
_Seed_
| Optional _<id>_ +
_Next Seed_
|=====

[cols="1a,1,5*3",width="100%"]
|=====
6+|[[OpClampStochasticRoundFToSINTEL]]*OpClampStochasticRoundFToSINTEL* +
 +
Converts value numerically from floating point to signed integer using stochastic rounding. +
 +
Has the same semantics as *OpStochasticRoundFToFINTEL*.
In case of NaN or overflow, the result is saturated to the nearest representable value
of _Result Type_. +
 +
_Result Type_ is the type of the converted value and must be a scalar or
vector of _integer type_. +
 +
_Value_ must be a scalar or vector of _floating-point type_. It must have a wider range
than the _Result Type_ and it must have the same number of components as _Result Type_. +
 +
_Seed_ must be a 32-bit scalar _integer type_. +
 +
_Next Seed_ must be of a _pointer type_ with *Function* storage class and 32-bit scalar _integer_ element type. +
 +
Results are computed per component. +
1+|Capability: +
*{f2s_capability_name}*
1+| 4+ | {OpClampStochasticRoundFToSINTEL_token}
| _<id>_ +
_Result Type_
| _Result <id>_
| _<id>_ +
_Value_
| _<id>_ +
_Seed_
| Optional _<id>_ +
_Next Seed_
|=====

=== Validation Rules

Add the following bullets to section 2.16.11, Universal Validation Rules:

* It is valid to use the *SaturatedToLargestFloat8NormalConversionEXT* decoration with *OpStochasticRoundFToFINTEL* when the _Result Type_ is *Float8E4M3EXT* or *Float8E5M2EXT*.

== Issues

. Why do we need *OpClampConvertFToSINTEL*? Can we just reuse *OpConvertFToS* with the *SaturatedConversion* decoration?
+
--
RESOLVED: Although it would be nice to reuse *OpConvertFToS*, *OpClampConvertFToSINTEL* has two key differences that warrant an additional instruction instead:

* The only supported rounding mode for *OpClampConvertFToSINTEL* is *RTE*, which is the default rounding mode, rather than *RTZ*.
* For NaN inputs, *OpClampConvertFToSINTEL* saturates to the nearest representable value, rather than converting to zero.
--

. Should it be valid to include the *SaturatedConversion* decoration on *OpClampConvertFToSINTEL* or *OpClampStochasticRoundFToSINTEL*?
+
--
RESOLVED: Due to the differing NaN behavior, it would be confusing to allow the *SaturatedConversion* decoration on *OpClampConvertFToSINTEL* or *OpClampStochasticRoundFToSINTEL*, therefore this is not valid.
--

== Revision History

[cols="5,15,15,70"]
[grid="rows"]
[options="header"]
|========================================
|Rev|Date|Author|Changes
|1|2024-06-15|Dmitry Sidorov|Initial revision
|1|2025-10-24|Dmitry Sidorov|Prepare to publish
|1|2026-05-28|Ben Ashbaugh|More preparations for publication
|========================================
