# DPCPP Version number information

if(NOT DEFINED DPCPP_VERSION_MAJOR)
  set(DPCPP_VERSION_MAJOR 6)
endif()
if(NOT DEFINED DPCPP_VERSION_MINOR)
  set(DPCPP_VERSION_MINOR 3)
endif()
if(NOT DEFINED DPCPP_VERSION_PATCH)
  set(DPCPP_VERSION_PATCH 0)
endif()

