# DPCPP Version number information

if(NOT DEFINED DPCPP_VERSION_MAJOR)
  set(DPCPP_VERSION_MAJOR 7)
endif()
if(NOT DEFINED DPCPP_VERSION_MINOR)
  set(DPCPP_VERSION_MINOR 0)
endif()
if(NOT DEFINED DPCPP_VERSION_PATCH)
  set(DPCPP_VERSION_PATCH 0)
endif()
  set(PRE_RELEASE 1)

