ZE ---> zeInit(ZE_INIT_FLAG_GPU_ONLY)
ZE ---> zeDriverGet(&ZeDriverCount, nullptr)
ZE ---> zeDriverGet(&ZeDriverCount, ZeDrivers.data())
ZE ---> zeDriverGetProperties(ZeDriver, &ZeDriverProperties)
ZE ---> zeDriverGetApiVersion(ZeDriver, &ZeApiVersion)
ZE ---> zeDriverGetExtensionProperties(ZeDriver, &Count, nullptr)
ZE ---> zeDriverGetExtensionProperties(ZeDriver, &Count, ZeExtensions.data())
ZE ---> zeDriverGetExtensionFunctionAddress(DriverHandle, "zexDriverImportExternalPointer", reinterpret_cast<void **>(&zexDriverImportExternalPointer))
ZE ---> zeDriverGetExtensionFunctionAddress(DriverHandle, "zexDriverReleaseImportedPointer", reinterpret_cast<void **>(&zexDriverReleaseImportedPointer))
ZE ---> zeDeviceGet(ZeDriver, &ZeDeviceCount, nullptr)
ZE ---> zeDeviceGet(ZeDriver, &ZeDeviceCount, ZeDevices.data())
ZE ---> zeDeviceGetProperties(ZeDevice, &Properties)
ZE ---> zeDeviceGetCommandQueueGroupProperties(ZeDevice, &numQueueGroups, nullptr)
NOTE: Number of queue groups = 1
ZE ---> zeDeviceGetCommandQueueGroupProperties(ZeDevice, &numQueueGroups, QueueGroupProperties.data())
NOTE: main blitter/copy engine is not available
NOTE: link blitter/copy engines are not available
ZE ---> zeDeviceGetSubDevices(Device->ZeDevice, &SubDevicesCount, nullptr)
ZE ---> zeDeviceGetSubDevices(Device->ZeDevice, &SubDevicesCount, ZeSubdevices)
ZE ---> zeDeviceGetModuleProperties(ZeDevice, &Properties)
ZE ---> zeDeviceGetImageProperties(ZeDevice, &Properties)
ZE ---> zeContextCreate(Platform->ZeDriver, &ContextDesc, &ZeContext)
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemGetAllocProperties(Context->ZeContext, Ptr, &AllocProperties, nullptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemAllocShared(Context->ZeContext, &ZeDevDesc, &ZeHostDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemGetAllocProperties(Context->ZeContext, Ptr, &AllocProperties, nullptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemAllocShared(Context->ZeContext, &ZeDevDesc, &ZeHostDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemGetAllocProperties(Context->ZeContext, Ptr, &AllocProperties, nullptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemAllocHost(Context->ZeContext, &ZeHostDesc, Size, Alignment, ResultPtr)
ZE ---> zeMemGetAllocProperties(Context->ZeContext, Ptr, &AllocProperties, nullptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeCommandListCreateImmediate(ZeContext, Device->ZeDevice, &ZeCommandQueueDesc, &ZeCommandListInit)
Running on device GPU (Intel(R) Iris(R) Xe Graphics [0x9a49]) Intel(R) Level-Zero plugin
Test zeMemAllocDevice
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemAllocDevice(Context->ZeContext, &ZeDesc, Size, Alignment, Device->ZeDevice, ResultPtr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
ZE ---> zeMemFree(Context->ZeContext, Ptr)
urQueueRelease(compute) NumTimesClosedFull 0, NumTimesClosedEarly 0
urQueueRelease(copy) NumTimesClosedFull 0, NumTimesClosedEarly 0
ZE ---> zeCommandListDestroy(ZeCommandListInit)
ZE ---> zeContextDestroy(DestroyZeContext)
