name: Runner Version Check

on: [push, pull_request]

jobs:
  check-runner-version:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: [self-hosted, Linux, X64, aux-tasks, dont_add_amdgpu_label, amdcpu]
            name: amdgpu-temp
          - runner: [self-hosted, Linux, X64, arc]
            name: arc_sycl01
          - runner: [self-hosted, Windows, X64, gen12]
            name: intel_sycl119890
          - runner: [self-hosted, Windows, X64, gen12]
            name: intel_sycl119893
          - runner: [self-hosted, Linux, X64, pvc]
            name: spr-05
          - runner: [temp_disabled]
            name: UR_DNP_06_PVC_03
          - runner: [self-hosted, Linux, X64, aux-tasks, pvc]
            name: UR_MOM_59_PVC
          - runner: [BMG_PERF, TEST_PERF]
            name: UR_PC_BMG_47

      fail-fast: false
    
    name: Check ${{ matrix.name }}
    
    steps:
      - name: Get Runner Version (Linux)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "checking runner version on Linux"

      - name: Get Runner Version (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "checking runner version on Windows"
