name: Bandit

on:
  workflow_dispatch:
  pull_request:
    branches:
    - sycl
    paths:
    - '**/*.py'
  push:
    branches:
    - sycl
    paths:
    - '**/*.py'

permissions:
  contents: read

jobs:
  bandit:
    if: github.repository == 'intel/llvm'
    name: Bandit
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Clone the git repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Bandit
        run: pip install bandit bandit-sarif-formatter

      - name: Run Bandit
        run: |
          bandit -c devops/bandit.config -r . --exit-zero -f sarif -o bandit_results.sarif

      - uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: bandit_results.sarif
