name: SYCL Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

permissions: read-all

jobs:
  # Build used for performance testing only: not intended for testing
  linux_shared_build:
    if: github.repository == 'intel/llvm'
    uses: ./.github/workflows/sycl-linux-build.yml
    secrets: inherit
    with:
      build_cache_root: "/__w/"
      build_cache_suffix: sprod_shared
      build_artifact_suffix: sprod_shared
      build_configure_extra_args: '--shared-libs --hip --cuda --native_cpu'
      build_target: all

      artifact_archive_name: sycl_linux_shared.tar.zst
