name: Zizmor

on:
  workflow_dispatch:
  push:
    branches:
      - sycl
    # Although workflow files (.yml) should only be placed in the
    # .github/workflows directory, composite actions may be placed anywhere.
    # Here in intel/llvm composite actions are placed in the devops/actions
    # directory. In llvm/llvm-project composite actions are placed right in the
    # .github/workflows directory. Therefore limiting the scanning to only these
    # directories. BUT we may consider scanning the entire repository to enhance
    # security.
    paths:
      - '.github/workflows/**/*.yml'
      - 'devops/actions/**/*.yml'
  pull_request:
    branches:
      - sycl
    paths:
      - '.github/workflows/**/*.yml'
      - 'devops/actions/**/*.yml'

permissions: {}

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/workflows/**/*.yml
            devops/actions/**/*.yml

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
