name: Build and Test Blender

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: true
      level_zero_dir:
        description: 'Root directory of Level Zero SDK installation'
        required: false
        type: string
        default: ''
      ccache_dir:
        description: 'ccache directory'
        required: true
        type: string
      toolchain_artifact:
        description: 'Artifact name for toolchain download'
        required: true
        type: string
      toolchain_artifact_filename:
        description: 'Toolchain artifact downloaded filename'
        required: true
        type: string

jobs:
  blender:
    runs-on: ${{ fromJSON(inputs.runner) }}
    container:
      image: ${{ contains(inputs.runner, 'Linux') && 'ghcr.io/intel/llvm/ubuntu2404_blender' || '' }}
      options: ${{ contains(inputs.runner, 'Linux') && '-u 1001 --device=/dev/dri -v /dev/dri/by-path:/dev/dri/by-path --privileged --cap-add SYS_ADMIN' || '' }}
    name: Build and Test Blender on ${{ contains(inputs.runner, 'Windows') && 'Windows' || 'Linux' }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: |
            devops/
          persist-credentials: false

      - name: Setup Environment Variables
        shell: bash
        run: |
          echo "OIDN_INSTALL_DIR=$GITHUB_WORKSPACE/oidn-install" >> $GITHUB_ENV
          echo "EMBREE_INSTALL_DIR=$GITHUB_WORKSPACE/embree-install" >> $GITHUB_ENV
          echo "BLENDER_INSTALL_DIR=$GITHUB_WORKSPACE/blender-install" >> $GITHUB_ENV
          echo "SYCL_INSTALL_DIR=$GITHUB_WORKSPACE/install" >> $GITHUB_ENV

      - name: Download Toolchain
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ inputs.toolchain_artifact }}

      - name: Extract Toolchain
        shell: bash
        env:
          TOOLCHAIN_ARTIFACT_FILENAME: ${{ inputs.toolchain_artifact_filename }}
        run: |
          rm -rf install
          mkdir install
          tar -xf $TOOLCHAIN_ARTIFACT_FILENAME -C install
          rm $TOOLCHAIN_ARTIFACT_FILENAME
          wget https://github.com/ispc/ispc/releases/download/v1.29.1/ispc-v1.29.1-linux.tar.gz
          tar xvf ispc-v1.29.1-linux.tar.gz -C install
          rm ispc-v1.29.1-linux.tar.gz
          echo "PATH=$PATH:$GITHUB_WORKSPACE/install:$GITHUB_WORKSPACE/install/ispc-v1.29.1-linux/bin:$GITHUB_WORKSPACE/install/ispc-v1.29.1-linux/lib:$GITHUB_WORKSPACE/install/ispc-v1.29.1-linux/" >> $GITHUB_ENV

      - name: Build OIDN
        uses: ./devops/actions/blender/oidn
        with:
          cmake_install_prefix: ${{ env.OIDN_INSTALL_DIR }}
          c_compiler: ${{ env.SYCL_INSTALL_DIR }}/bin/clang${{ runner.os == 'Windows' && '.exe' || '' }}
          cxx_compiler: ${{ env.SYCL_INSTALL_DIR }}/bin/clang++${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Build Embree
        uses: ./devops/actions/blender/embree
        with:
          cmake_install_prefix: ${{ env.EMBREE_INSTALL_DIR }}
          c_compiler: ${{ env.SYCL_INSTALL_DIR }}/bin/clang${{ runner.os == 'Windows' && '.exe' || '' }}
          cxx_compiler: ${{ env.SYCL_INSTALL_DIR }}/bin/clang++${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Build Blender
        uses: ./devops/actions/blender/blender-build
        with:
          oidn_dir: ${{ env.OIDN_INSTALL_DIR }}
          embree_dir: ${{ env.EMBREE_INSTALL_DIR }}
          level_zero_dir: ${{ inputs.level_zero_dir }}
          cmake_install_prefix: ${{ env.BLENDER_INSTALL_DIR }}
          sycl_dir: ${{ env.SYCL_INSTALL_DIR }}
          ccache_dir: ${{ inputs.ccache_dir }}

      - name: Run Blender Classroom Demo
        uses: ./devops/actions/blender/blender-demo
        with:
          blender_dir: ${{ env.BLENDER_INSTALL_DIR }}

      - name: Cleanup
        shell: bash
        if: always()
        run: |
          rm -rf "$OIDN_INSTALL_DIR" "$EMBREE_INSTALL_DIR" "$BLENDER_INSTALL_DIR"
  