name: SYCL Post Commit

on:
  workflow_dispatch:

  push:
    branches:
    - sycl
    - sycl-rel-**

  pull_request:
    branches:
    - sycl
    paths:
    - .github/workflows/sycl-post-commit.yml
    - .github/workflows/sycl-linux-build.yml
    - .github/workflows/sycl-linux-run-tests.yml
    - .github/workflows/sycl-macos-build-and-test.yml
    - ./devops/actions/cleanup
    - ./devops/actions/cached_checkout
    - ./devops/dependencies.json
    - ./devops/dependencies-igc-dev.json

concurrency:
  #  Cancel a currently running workflow from the same PR or commit hash.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-win:
    if: |
      always()
      && success()
      && github.repository == 'intel/llvm'
    uses: ./.github/workflows/sycl-windows-build.yml
    with:
      cxx: icx
      build_configure_extra_args: -DCMAKE_C_FLAGS="/clang:-Wno-nonportable-include-path /clang:-Wno-cast-function-type-mismatch" -DCMAKE_CXX_FLAGS="/clang:-Wno-nonportable-include-path /clang:-Wno-cast-function-type-mismatch"
      build_cache_suffix: icx

  e2e-win:
    needs: build-win
    # Continue if build was successful.
    if: |
      always()
      && !cancelled()
      && needs.build-win.outputs.build_conclusion == 'success'
    uses: ./.github/workflows/sycl-windows-run-tests.yml
    with:
      name: Intel GEN12 Graphics with Level Zero
      runner: '["Windows","gen12"]'
      target_devices: "level_zero:gpu"
      sycl_toolchain_archive: ${{ needs.build-win.outputs.artifact_archive_name }}
      cxx: icx
      env: "{'LIT_FILTER':'std_array'}"
