name: (TEST) Hijacking aggregate workflow for testing

# The benchmarking workflow in sycl-linux-run-tests.yml passes or fails based on
# how the benchmark results compare to a historical average: This historical
# average is calculated in this workflow, which aggregates historical data and
# produces measures of central tendency (median in this case) used for this
# purpose.

on:
  workflow_dispatch:
    inputs:
      pr_no:
        description: Specific PR no. to build
        type: number
        required: false
      upload_results:
        description: 'Save and upload results'
        type: choice
        options:
          - false
          - true
        default: true
      runner:
        type: choice
        options:
          - '["PVC_PERF"]'
      backend:
        description: Backend to use
        type: choice
        options:
          - 'level_zero:gpu'
        # TODO L0 V2 support
      reset_intel_gpu:
        description: Reset Intel GPUs
        type: choice
        options:
          - false
          - true
        default: true

permissions:
  contents: read
  packages: read

jobs:
  aggregate:
    name: Test benchmark.yml
    uses: ./.github/workflows/benchmark.yml
    secrets: inherit
    with:
      pr_no: ${{ inputs.pr_no }}
      upload_results: ${{ inputs.upload_results }}
      runner: ${{ inputs.runner }}
      backend: ${{ inputs.backend }}
      reset_intel_gpu: ${{ inputs.reset_intel_gpu }}
